/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DailyTaskPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/models/settings.ts
var DEFAULT_TEMPLATE_ZH = `# {{dateWithIcon}}| {{weekday}}

### \u{1F9D8} \u4ECA\u65E5\u8BA1\u5212
---

- [ ] \u51A5\u60F3 10 \u5206\u949F  
- [ ] \u590D\u76D8\u524D\u4E00\u65E5\u8BA1\u5212  
- [ ] \u9605\u8BFB 20 \u9875\u4E66

### \u{1F4DD} \u5DE5\u4F5C\u4EFB\u52A1
---

- [ ] \u6574\u7406\u4ECA\u65E5\u5DE5\u4F5C\u8BA1\u5212
- [ ] \u5B8C\u6210\u91CD\u8981\u9879\u76EE\u8FDB\u5EA6
`;
var DEFAULT_TEMPLATE_EN = `# {{dateWithIcon}}| {{weekday}}

### \u{1F9D8} Today's Plan
---

- [ ] Meditate for 10 minutes  
- [ ] Review yesterday's plan  
- [ ] Read 20 pages

### \u{1F4DD} Work Tasks
---

- [ ] Organize today's work schedule
- [ ] Progress on important projects
`;
var DEFAULT_SETTINGS = {
  rootDir: "DailyTasks",
  autoGenerateMode: "workday" /* WORKDAY */,
  language: "auto" /* AUTO */,
  fileGenerationMode: "monthly" /* MONTHLY */,
  // 默认按月度生成
  dailyFilePrefix: "",
  // 默认无前缀
  templateZh: DEFAULT_TEMPLATE_ZH,
  templateEn: DEFAULT_TEMPLATE_EN,
  customTemplate: "",
  // 默认为空，表示使用语言相关的默认模板
  hasCustomTemplate: false,
  // 默认不使用自定义模板
  taskStatistics: false,
  // 默认关闭任务统计功能
  statisticsMaxSuggestions: 5,
  statisticsIncludeWeekends: true,
  successNotificationDuration: 3e3
};

// src/settings/settings.ts
var import_obsidian3 = require("obsidian");

// src/i18n/i18n.ts
var translationsZH = {
  // 设置页面
  "settings.title": "\u6BCF\u65E5\u4EFB\u52A1\u81EA\u52A8\u751F\u6210\u5668",
  "settings.rootDir": "\u{1F5C2}\uFE0F \u4EFB\u52A1\u6587\u4EF6\u5B58\u653E\u76EE\u5F55",
  "settings.rootDir.desc": "\u6240\u6709\u4EFB\u52A1\u6587\u4EF6\u5C06\u5B58\u653E\u5728\u6B64\u76EE\u5F55\u4E0B\uFF0C\u6309\u5E74\u4EFD\u548C\u6708\u4EFD\u7EC4\u7EC7",
  "settings.rootDir.saved": "\u2713 \u76EE\u5F55\u5DF2\u4FDD\u5B58",
  "settings.save": "\u{1F4BE} \u4FDD\u5B58",
  "settings.autoGenerate": "\u2699\uFE0F \u81EA\u52A8\u751F\u6210\u6A21\u5F0F",
  "settings.autoGenerate.desc": "\u9009\u62E9\u4F55\u65F6\u81EA\u52A8\u751F\u6210\u4EFB\u52A1",
  "settings.mode.none": "\u5173\u95ED",
  "settings.mode.daily": "\u6BCF\u65E5",
  "settings.mode.workday": "\u5DE5\u4F5C\u65E5",
  "settings.fileGenerationMode": "\u{1F4C1} \u6587\u4EF6\u751F\u6210\u6A21\u5F0F",
  "settings.fileGenerationMode.desc": "\u9009\u62E9\u4EFB\u52A1\u6587\u4EF6\u7684\u7EC4\u7EC7\u65B9\u5F0F",
  "settings.fileMode.monthly": "\u6309\u6708\u5EA6\u751F\u6210\uFF08\u8FFD\u52A0\u5230\u6708\u4EFD\u6587\u4EF6\uFF09",
  "settings.fileMode.daily": "\u6309\u65E5\u5EA6\u751F\u6210\uFF08\u6BCF\u65E5\u72EC\u7ACB\u6587\u4EF6\uFF09",
  "settings.dailyFilePrefix": "\u{1F4DD} \u65E5\u5EA6\u6587\u4EF6\u524D\u7F00",
  "settings.dailyFilePrefix.desc": "\u65E5\u5EA6\u6A21\u5F0F\u4E0B\u6587\u4EF6\u540D\u7684\u524D\u7F00\uFF08\u53EF\u9009\uFF09",
  "settings.dailyFilePrefix.placeholder": "\u4F8B\u5982\uFF1A\u5927\u738B\u6765\u5DE1\u5C71\u7684\u7504\u9009\u7B14\u8BB0",
  "settings.language": "\u{1F310} \u754C\u9762\u8BED\u8A00",
  "settings.language.desc": "\u9009\u62E9\u63D2\u4EF6\u754C\u9762\u8BED\u8A00",
  "settings.language.auto": "\u81EA\u52A8\u68C0\u6D4B",
  "settings.language.zh": "\u4E2D\u6587",
  "settings.language.en": "English",
  "settings.animations": "\u2728 \u52A8\u753B\u6548\u679C",
  "settings.animations.desc": "\u542F\u7528\u754C\u9762\u52A8\u753B\u6548\u679C",
  "settings.template": "\u{1F4DD} \u4EFB\u52A1\u6A21\u677F",
  "settings.template.zh": "\u{1F1E8}\u{1F1F3} \u4E2D\u6587\u6A21\u677F",
  "settings.template.en": "\u{1F1EC}\u{1F1E7} \u82F1\u6587\u6A21\u677F",
  "settings.template.desc": "\u81EA\u5B9A\u4E49\u6BCF\u65E5\u4EFB\u52A1\u7684\u6A21\u677F\u5185\u5BB9\uFF08\u7559\u7A7A\u4F7F\u7528\u9ED8\u8BA4\u6A21\u677F\uFF09",
  "settings.template.placeholder": "\u8F93\u5165\u81EA\u5B9A\u4E49\u6A21\u677F...",
  "settings.template.preview": "\u{1F440} \u9884\u89C8\u6A21\u677F",
  "settings.template.hide": "\u{1F441}\uFE0F\u200D\u{1F5E8}\uFE0F \u9690\u85CF\u9884\u89C8",
  "settings.template.restoreDefault": "\u6062\u590D\u9ED8\u8BA4\u6A21\u677F",
  "settings.template.resetAll": "\u91CD\u7F6E\u6240\u6709\u8BBE\u7F6E",
  "settings.resetToDefault": "\u{1F504} \u6062\u590D\u9ED8\u8BA4\u8BBE\u7F6E",
  "settings.restoreTemplate": "\u{1F4C4} \u6062\u590D\u9ED8\u8BA4\u6A21\u677F",
  "settings.addTask": "\u2795 \u624B\u52A8\u6DFB\u52A0\u4ECA\u65E5\u4EFB\u52A1",
  "settings.addTask.desc": "\u7ACB\u5373\u4E3A\u4ECA\u5929\u6DFB\u52A0\u4EFB\u52A1\u5185\u5BB9",
  "settings.addTaskButton": "\u2795 \u624B\u52A8\u6DFB\u52A0\u4ECA\u65E5\u4EFB\u52A1",
  "settings.resetDefault": "\u{1F504} \u6062\u590D\u9ED8\u8BA4\u8BBE\u7F6E",
  "settings.notificationDuration": "\u23F1\uFE0F \u901A\u77E5\u663E\u793A\u65F6\u95F4",
  "settings.notificationDuration.desc": "\u6210\u529F/\u5931\u8D25\u63D0\u793A\u663E\u793A\u65F6\u95F4\uFF08\u6BEB\u79D2\uFF09",
  "settings.preview": "\u9884\u89C8\u6A21\u677F\u6548\u679C",
  "settings.basicSettings": "\u57FA\u672C\u8BBE\u7F6E",
  "settings.templateSettings": "\u6A21\u677F\u8BBE\u7F6E",
  "template.dateWithIcon": "\u5E26\u56FE\u6807\u7684\u5F53\u524D\u65E5\u671F",
  // 任务统计设置
  "settings.taskStatistics": "\u{1F4CA} \u4EFB\u52A1\u5B8C\u6210\u7EDF\u8BA1",
  "settings.taskStatistics.desc": "\u5F00\u542F\u540E\uFF0C\u6BCF\u65E5\u751F\u6210\u4EFB\u52A1\u524D\u4F1A\u81EA\u52A8\u7EDF\u8BA1\u524D\u4E00\u5929\u7684\u4EFB\u52A1\u5B8C\u6210\u60C5\u51B5",
  "settings.statisticsMaxSuggestions": "\u{1F4CB} \u6700\u5927\u5EFA\u8BAE\u4EFB\u52A1\u6570",
  "settings.statisticsMaxSuggestions.desc": "\u7EDF\u8BA1\u4E2D\u6700\u591A\u663E\u793A\u591A\u5C11\u4E2A\u672A\u5B8C\u6210\u4EFB\u52A1\u5EFA\u8BAE",
  "settings.statisticsIncludeWeekends": "\u{1F4C5} \u5305\u542B\u5468\u672B\u7EDF\u8BA1",
  "settings.statisticsIncludeWeekends.desc": "\u5DE5\u4F5C\u65E5\u6A21\u5F0F\u4E0B\u662F\u5426\u7EDF\u8BA1\u5468\u672B\u7684\u4EFB\u52A1\uFF08\u5173\u95ED\u65F6\u5468\u4E00\u53EA\u7EDF\u8BA1\u4E0A\u5468\u4E94\u7684\u4EFB\u52A1\uFF09",
  // 通知消息
  "notification.taskAdded": "\u4ECA\u65E5\u4EFB\u52A1\u5DF2\u6DFB\u52A0",
  "notification.taskExists": "\u4ECA\u65E5\u4EFB\u52A1\u5DF2\u5B58\u5728",
  "notification.fileExists": "\u4ECA\u65E5\u4EFB\u52A1\u6587\u4EF6\u5DF2\u5B58\u5728",
  "notification.generating": "\u6B63\u5728\u751F\u6210\u4EFB\u52A1...",
  "notification.error": "\u9519\u8BEF\uFF1A",
  "notification.folderCreated": "\u6587\u4EF6\u5939\u5DF2\u521B\u5EFA",
  // 星期
  "weekday.mon": "\u661F\u671F\u4E00",
  "weekday.tue": "\u661F\u671F\u4E8C",
  "weekday.wed": "\u661F\u671F\u4E09",
  "weekday.thu": "\u661F\u671F\u56DB",
  "weekday.fri": "\u661F\u671F\u4E94",
  "weekday.sat": "\u661F\u671F\u516D",
  "weekday.sun": "\u661F\u671F\u65E5",
  // 插件名称和描述
  "plugin.name": "\u6BCF\u65E5\u4EFB\u52A1\u81EA\u52A8\u751F\u6210\u5668",
  "plugin.description": "\u4E00\u4E2A\u5F3A\u5927\u7684\u4EFB\u52A1\u81EA\u52A8\u751F\u6210\u5668\uFF0C\u5E2E\u52A9\u4F60\u9AD8\u6548\u5730\u7BA1\u7406\u65E5\u5E38\u4EFB\u52A1",
  // 一般按钮和消息
  "button.addTask": "\u6DFB\u52A0\u4EFB\u52A1",
  "button.save": "\u4FDD\u5B58",
  "button.cancel": "\u53D6\u6D88",
  "button.done": "\u5B8C\u6210",
  // 任务统计相关翻译
  "statistics.title": "\u{1F4CA} \u6628\u65E5\u4EFB\u52A1\u7EDF\u8BA1",
  "statistics.totalTasks": "\u4EFB\u52A1\u603B\u6570",
  "statistics.completedTasks": "\u5DF2\u5B8C\u6210\u4EFB\u52A1",
  "statistics.completionRate": "\u5B8C\u6210\u7387",
  "statistics.unfinishedTasks": "\u672A\u5B8C\u6210\u7684\u4EFB\u52A1",
  "statistics.suggestions": "\u5EFA\u8BAE\u4ECA\u65E5\u8003\u8651\u5B8C\u6210\u4EE5\u4E0B\u4EFB\u52A1",
  "statistics.moreTasks.singular": "\u8FD8\u6709 1 \u4E2A\u4EFB\u52A1",
  "statistics.moreTasks.plural": "\u4E2A\u4EFB\u52A1"
};
var translationsEN = {
  // 设置页面
  "settings.title": "Daily Task Auto Generator",
  "settings.rootDir": "\u{1F5C2}\uFE0F Task File Directory",
  "settings.rootDir.desc": "All task files will be stored in this directory, organized by year and month",
  "settings.rootDir.saved": "\u2713 Directory saved",
  "settings.save": "\u{1F4BE} Save",
  "settings.autoGenerate": "\u2699\uFE0F Auto Generate Mode",
  "settings.autoGenerate.desc": "Choose when to automatically generate tasks",
  "settings.mode.none": "Off",
  "settings.mode.daily": "Daily",
  "settings.mode.workday": "Workdays",
  "settings.fileGenerationMode": "\u{1F4C1} File Generation Mode",
  "settings.fileGenerationMode.desc": "Choose how to organize task files",
  "settings.fileMode.monthly": "Monthly (append to month file)",
  "settings.fileMode.daily": "Daily (separate file per day)",
  "settings.dailyFilePrefix": "\u{1F4DD} Daily File Prefix",
  "settings.dailyFilePrefix.desc": "Optional prefix for daily mode filenames",
  "settings.dailyFilePrefix.placeholder": "e.g., MyDaily",
  "settings.language": "\u{1F310} Interface Language",
  "settings.language.desc": "Select the interface language",
  "settings.language.auto": "Auto Detect",
  "settings.language.zh": "\u4E2D\u6587",
  "settings.language.en": "English",
  "settings.animations": "\u2728 Animation Effects",
  "settings.animations.desc": "Enable interface animation effects",
  "settings.template": "\u{1F4DD} Task Template",
  "settings.template.zh": "\u{1F1E8}\u{1F1F3} Chinese Template",
  "settings.template.en": "\u{1F1EC}\u{1F1E7} English Template",
  "settings.template.desc": "Customize the daily task template content (leave empty to use default)",
  "settings.template.placeholder": "Enter custom template...",
  "settings.template.preview": "\u{1F440} Preview Template",
  "settings.template.hide": "\u{1F441}\uFE0F\u200D\u{1F5E8}\uFE0F Hide Preview",
  "settings.template.restoreDefault": "Restore Default Template",
  "settings.template.resetAll": "Reset All Settings",
  "settings.resetToDefault": "\u{1F504} Reset to Default",
  "settings.restoreTemplate": "\u{1F4C4} Restore Default Template",
  "settings.addTask": "\u2795 Add Today's Task Manually",
  "settings.addTask.desc": "Add task content for today immediately",
  "settings.addTaskButton": "\u2795 Add Today's Task Manually",
  "settings.resetDefault": "\u{1F504} Reset to Default",
  "settings.notificationDuration": "\u23F1\uFE0F Notification Duration",
  "settings.notificationDuration.desc": "Duration for success/failure notifications (milliseconds)",
  "settings.preview": "Preview template effect",
  "settings.basicSettings": "Basic Settings",
  "settings.templateSettings": "Template Settings",
  "template.dateWithIcon": "Current date with icon",
  // 任务统计设置
  "settings.taskStatistics": "\u{1F4CA} Task Completion Statistics",
  "settings.taskStatistics.desc": "When enabled, automatically analyze yesterday's task completion before generating today's tasks",
  "settings.statisticsMaxSuggestions": "\u{1F4CB} Max Suggested Tasks",
  "settings.statisticsMaxSuggestions.desc": "Maximum number of unfinished tasks to show in statistics",
  "settings.statisticsIncludeWeekends": "\u{1F4C5} Include Weekend Statistics",
  "settings.statisticsIncludeWeekends.desc": "In workday mode, whether to include weekend tasks in statistics (when off, Monday only analyzes Friday's tasks)",
  // 通知消息
  "notification.taskAdded": "Today's task has been added",
  "notification.taskExists": "Today's task already exists",
  "notification.fileExists": "Today's task file already exists",
  "notification.generating": "Generating tasks...",
  "notification.error": "Error: ",
  "notification.folderCreated": "Folder created",
  // 星期
  "weekday.mon": "Monday",
  "weekday.tue": "Tuesday",
  "weekday.wed": "Wednesday",
  "weekday.thu": "Thursday",
  "weekday.fri": "Friday",
  "weekday.sat": "Saturday",
  "weekday.sun": "Sunday",
  // 插件名称和描述
  "plugin.name": "Daily Task Auto Generator",
  "plugin.description": "A powerful task auto generator to help you efficiently manage daily tasks",
  // 一般按钮和消息
  "button.addTask": "Add Task",
  "button.save": "Save",
  "button.cancel": "Cancel",
  "button.done": "Done",
  // 任务统计相关翻译
  "statistics.title": "\u{1F4CA} Yesterday's Task Summary",
  "statistics.totalTasks": "Total Tasks",
  "statistics.completedTasks": "Completed Tasks",
  "statistics.completionRate": "Completion Rate",
  "statistics.unfinishedTasks": "Unfinished Tasks",
  "statistics.suggestions": "Consider completing the following tasks today",
  "statistics.moreTasks.singular": "1 more task",
  "statistics.moreTasks.plural": "more tasks"
};
var translations = {
  "zh": translationsZH,
  "en": translationsEN
};
var currentLanguage = "en";
function setCurrentLanguage(language) {
  currentLanguage = language;
}
function getTranslation(key, fallbackLanguage) {
  var _a, _b;
  const lang = fallbackLanguage || currentLanguage;
  const translation = (_a = translations[lang]) == null ? void 0 : _a[key];
  if (translation) {
    return translation;
  }
  if (lang !== "en") {
    return ((_b = translations["en"]) == null ? void 0 : _b[key]) || key;
  }
  return key;
}
function getLocalizedWeekday(dayOfWeek) {
  const weekdays = [
    "weekday.sun",
    "weekday.mon",
    "weekday.tue",
    "weekday.wed",
    "weekday.thu",
    "weekday.fri",
    "weekday.sat"
  ];
  return getTranslation(weekdays[dayOfWeek] || "weekday.sun");
}

// src/utils/dateUtils.ts
function getCurrentYear() {
  return new Date().getFullYear().toString();
}
function getCurrentMonth() {
  const month = (new Date().getMonth() + 1).toString();
  return month.padStart(2, "0");
}
function getLocalizedMonthName(isEnglish = false) {
  const monthIndex = new Date().getMonth();
  const chineseMonths = [
    "1\u6708",
    "2\u6708",
    "3\u6708",
    "4\u6708",
    "5\u6708",
    "6\u6708",
    "7\u6708",
    "8\u6708",
    "9\u6708",
    "10\u6708",
    "11\u6708",
    "12\u6708"
  ];
  const englishMonths = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December"
  ];
  return isEnglish ? englishMonths[monthIndex] : chineseMonths[monthIndex];
}
function getDayIcon() {
  const day = new Date().getDate();
  const dayIcons = [
    "\u{1F311}",
    // 1日
    "\u{1F312}",
    // 2日
    "\u{1F313}",
    // 3日
    "\u{1F314}",
    // 4日
    "\u{1F315}",
    // 5日
    "\u{1F316}",
    // 6日
    "\u{1F317}",
    // 7日
    "\u{1F318}",
    // 8日
    "\u{1F31F}",
    // 9日
    "\u2B50",
    // 10日
    "\u{1F308}",
    // 11日
    "\u{1F31E}",
    // 12日
    "\u{1F324}\uFE0F",
    // 13日
    "\u26C5",
    // 14日
    "\u{1F326}\uFE0F",
    // 15日
    "\u{1F327}\uFE0F",
    // 16日
    "\u26C8\uFE0F",
    // 17日
    "\u{1F329}\uFE0F",
    // 18日
    "\u{1F32A}\uFE0F",
    // 19日
    "\u{1F32B}\uFE0F",
    // 20日
    "\u{1F32C}\uFE0F",
    // 21日
    "\u{1F340}",
    // 22日
    "\u{1F331}",
    // 23日
    "\u{1F332}",
    // 24日
    "\u{1F333}",
    // 25日
    "\u{1F334}",
    // 26日
    "\u{1F335}",
    // 27日
    "\u{1F33A}",
    // 28日
    "\u{1F33B}",
    // 29日
    "\u{1F33C}",
    // 30日
    "\u{1F338}"
    // 31日
  ];
  return dayIcons[day - 1] || "\u{1F4C5}";
}
function isEnglishEnvironment() {
  const mondayText = getTranslation("weekday.mon");
  return mondayText === "Monday";
}
function getCurrentDay() {
  const day = new Date().getDate().toString();
  return day.padStart(2, "0");
}
function getCurrentDate() {
  return `${getCurrentYear()}-${getCurrentMonth()}-${getCurrentDay()}`;
}
function getCurrentDateWithIcon() {
  const icon = getDayIcon();
  return `${icon} ${getCurrentDate()}`;
}
function isWorkday() {
  const day = new Date().getDay();
  return day >= 1 && day <= 5;
}
function getCurrentWeekdayName() {
  const day = new Date().getDay();
  return getLocalizedWeekday(day);
}
function getYearProgress() {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 1);
  const end = new Date(now.getFullYear() + 1, 0, 1);
  const totalDays = (end.getTime() - start.getTime()) / (1e3 * 60 * 60 * 24);
  const passedDays = (now.getTime() - start.getTime()) / (1e3 * 60 * 60 * 24);
  return Math.round(passedDays / totalDays * 100);
}
function getMonthProgress() {
  const now = new Date();
  const start = new Date(now.getFullYear(), now.getMonth(), 1);
  const end = new Date(now.getFullYear(), now.getMonth() + 1, 1);
  const totalDays = (end.getTime() - start.getTime()) / (1e3 * 60 * 60 * 24);
  const passedDays = (now.getTime() - start.getTime()) / (1e3 * 60 * 60 * 24);
  return Math.round(passedDays / totalDays * 100);
}
function getLastWorkdayDate(daysBack = 1) {
  const today = new Date();
  const date = new Date(today);
  date.setDate(today.getDate() - daysBack);
  console.log(`[DEBUG] \u5DE5\u4F5C\u65E5\u8BA1\u7B97 - \u5F00\u59CB\u65E5\u671F: ${date.toISOString().split("T")[0]} (${getWeekdayName(date.getDay())})`);
  let iterations = 0;
  while (date.getDay() === 0 || date.getDay() === 6) {
    date.setDate(date.getDate() - 1);
    iterations++;
    console.log(`[DEBUG] \u5DE5\u4F5C\u65E5\u8BA1\u7B97 - \u8DF3\u8FC7\u5468\u672B\uFF0C\u56DE\u9000\u5230: ${date.toISOString().split("T")[0]} (${getWeekdayName(date.getDay())})`);
    if (iterations > 7) {
      console.error(`[DEBUG] \u5DE5\u4F5C\u65E5\u8BA1\u7B97 - \u5F02\u5E38\uFF1A\u56DE\u9000\u8D85\u8FC77\u5929`);
      break;
    }
  }
  const year = date.getFullYear();
  const month = (date.getMonth() + 1).toString().padStart(2, "0");
  const day = date.getDate().toString().padStart(2, "0");
  const result = `${year}-${month}-${day}`;
  console.log(`[DEBUG] \u5DE5\u4F5C\u65E5\u8BA1\u7B97 - \u6700\u7EC8\u7ED3\u679C: ${result} (${getWeekdayName(date.getDay())})`);
  return result;
}
function getWeekdayName(dayOfWeek) {
  const weekdays = ["\u5468\u65E5", "\u5468\u4E00", "\u5468\u4E8C", "\u5468\u4E09", "\u5468\u56DB", "\u5468\u4E94", "\u5468\u516D"];
  return weekdays[dayOfWeek] || "\u672A\u77E5";
}

// src/utils/templateEngine.ts
function getCurrentTime() {
  const now = new Date();
  const hours = now.getHours().toString().padStart(2, "0");
  const minutes = now.getMinutes().toString().padStart(2, "0");
  return `${hours}:${minutes}`;
}
function renderTemplate(template) {
  const variableMap = {
    "date": getCurrentDate(),
    "dateWithIcon": getCurrentDateWithIcon(),
    "weekday": getCurrentWeekdayName(),
    "yearProgress": getYearProgress(),
    "monthProgress": getMonthProgress(),
    "time": getCurrentTime()
  };
  let renderedContent = template;
  for (const [variable, value] of Object.entries(variableMap)) {
    renderedContent = renderedContent.replace(
      new RegExp(`{{${variable}}}`, "g"),
      value.toString()
    );
  }
  return renderedContent;
}

// src/taskGenerator.ts
var import_obsidian2 = require("obsidian");

// src/utils/fileUtils.ts
var import_obsidian = require("obsidian");
async function ensureFolderExists(vault, path) {
  try {
    path = path.endsWith("/") ? path : path + "/";
    const folders = path.split("/").filter((p) => p.length > 0);
    let currentPath = "";
    for (const folder of folders) {
      if (currentPath) {
        currentPath += "/" + folder;
      } else {
        currentPath = folder;
      }
      console.log(`\u68C0\u67E5\u76EE\u5F55: ${currentPath}`);
      const existingItem = vault.getAbstractFileByPath(currentPath);
      if (!existingItem) {
        console.log(`\u76EE\u5F55\u4E0D\u5B58\u5728\uFF0C\u6B63\u5728\u521B\u5EFA: ${currentPath}`);
        try {
          await vault.createFolder(currentPath);
          console.log(`\u76EE\u5F55\u521B\u5EFA\u6210\u529F: ${currentPath}`);
        } catch (e) {
          console.log(`\u521B\u5EFA\u76EE\u5F55\u65F6\u51FA\u73B0\u5F02\u5E38\uFF0C\u53EF\u80FD\u5DF2\u88AB\u5176\u4ED6\u8FDB\u7A0B\u521B\u5EFA: ${e}`);
          const folderAfterError = vault.getAbstractFileByPath(currentPath);
          if (!folderAfterError || !(folderAfterError instanceof import_obsidian.TFolder)) {
            console.error(`\u76EE\u5F55\u521B\u5EFA\u5931\u8D25\uFF0C\u4E14\u65E0\u6CD5\u786E\u8BA4\u76EE\u5F55\u5DF2\u5B58\u5728: ${currentPath}`);
            return false;
          }
        }
      } else if (!(existingItem instanceof import_obsidian.TFolder)) {
        console.error(`\u8DEF\u5F84 ${currentPath} \u5DF2\u5B58\u5728\u4F46\u4E0D\u662F\u6587\u4EF6\u5939\uFF0C\u800C\u662F: ${existingItem.constructor.name}`);
        return false;
      } else {
        console.log(`\u76EE\u5F55\u5DF2\u5B58\u5728\uFF0C\u65E0\u9700\u521B\u5EFA: ${currentPath}`);
      }
    }
    return true;
  } catch (error) {
    console.error(`\u521B\u5EFA\u76EE\u5F55\u65F6\u51FA\u73B0\u672A\u9884\u671F\u9519\u8BEF(${path}):`, error);
    return false;
  }
}
async function ensureFileExists(vault, path, content = "") {
  try {
    const existingItem = vault.getAbstractFileByPath(path);
    if (existingItem) {
      if (existingItem instanceof import_obsidian.TFile) {
        console.log(`\u6587\u4EF6\u5DF2\u5B58\u5728\uFF0C\u65E0\u9700\u521B\u5EFA: ${path}`);
        return true;
      } else {
        console.error(`\u8DEF\u5F84 ${path} \u5B58\u5728\u4F46\u4E0D\u662F\u6587\u4EF6\uFF0C\u65E0\u6CD5\u521B\u5EFA\u6587\u4EF6\uFF0C\u53EF\u80FD\u662F\u540C\u540D\u76EE\u5F55`);
        return false;
      }
    }
    const lastSlashIndex = path.lastIndexOf("/");
    if (lastSlashIndex > 0) {
      const parentPath = path.substring(0, lastSlashIndex);
      console.log(`\u68C0\u67E5\u6587\u4EF6\u7236\u76EE\u5F55: ${parentPath}`);
      const parentExists = await ensureFolderExists(vault, parentPath);
      if (!parentExists) {
        console.error(`\u65E0\u6CD5\u786E\u4FDD\u7236\u76EE\u5F55\u5B58\u5728: ${parentPath}`);
        return false;
      }
    }
    try {
      console.log(`\u5F00\u59CB\u521B\u5EFA\u6587\u4EF6: ${path}`);
      await vault.create(path, content);
      console.log(`\u6587\u4EF6\u521B\u5EFA\u6210\u529F: ${path}`);
      return true;
    } catch (e) {
      console.log(`\u521B\u5EFA\u6587\u4EF6\u65F6\u51FA\u73B0\u5F02\u5E38: ${e}`);
      const fileAfterError = vault.getAbstractFileByPath(path);
      if (fileAfterError && fileAfterError instanceof import_obsidian.TFile) {
        console.log(`\u5C3D\u7BA1\u51FA\u73B0\u5F02\u5E38\uFF0C\u4F46\u6587\u4EF6\u5DF2\u5B58\u5728\uFF0C\u53EF\u80FD\u88AB\u5176\u4ED6\u8FDB\u7A0B\u521B\u5EFA: ${path}`);
        return true;
      }
      console.error(`\u6587\u4EF6\u521B\u5EFA\u6700\u7EC8\u5931\u8D25: ${path}`);
      return false;
    }
  } catch (error) {
    console.error(`\u521B\u5EFA\u6587\u4EF6\u65F6\u51FA\u73B0\u672A\u9884\u671F\u9519\u8BEF(${path}):`, error);
    return false;
  }
}
async function appendToFile(vault, path, content) {
  try {
    const file = vault.getAbstractFileByPath(path);
    if (file && file instanceof import_obsidian.TFile) {
      try {
        const currentContent = await vault.read(file);
        await vault.modify(file, currentContent + "\n\n" + content);
        return true;
      } catch (e) {
        console.error(`\u8BFB\u53D6\u6216\u4FEE\u6539\u6587\u4EF6\u65F6\u51FA\u9519: ${e}`);
        return false;
      }
    } else {
      console.log(`\u6587\u4EF6\u4E0D\u5B58\u5728\uFF0C\u5C1D\u8BD5\u521B\u5EFA: ${path}`);
      return await ensureFileExists(vault, path, content);
    }
  } catch (error) {
    console.error(`Error appending to file at ${path}:`, error);
    return false;
  }
}
function getTaskFilePath(rootDir) {
  const year = getCurrentYear();
  const isEnglish = isEnglishEnvironment();
  const monthName = getLocalizedMonthName(isEnglish);
  return `${rootDir}/${year}/${monthName}.md`;
}
function getDailyTaskFilePath(rootDir, filePrefix = "") {
  const year = getCurrentYear();
  const month = getCurrentMonth();
  const date = getCurrentDate();
  const fileName = filePrefix ? `${filePrefix}${date}.md` : `${date}.md`;
  return `${rootDir}/${year}/${month.toString().padStart(2, "0")}/${fileName}`;
}
function getYesterdayDailyTaskFilePath(rootDir, filePrefix = "", isWorkdayMode = false) {
  const yesterdayDate = isWorkdayMode ? getLastWorkdayDate(1) : getYesterdayDate();
  const targetDate = new Date(yesterdayDate);
  const year = targetDate.getFullYear();
  const month = targetDate.getMonth() + 1;
  const fileName = filePrefix ? `${filePrefix}${yesterdayDate}.md` : `${yesterdayDate}.md`;
  return `${rootDir}/${year}/${month.toString().padStart(2, "0")}/${fileName}`;
}
async function ensureDailyFolderStructure(vault, rootDir, filePrefix = "") {
  try {
    const year = getCurrentYear();
    const month = getCurrentMonth();
    const rootCreated = await ensureFolderExists(vault, rootDir);
    if (!rootCreated) {
      return false;
    }
    const yearFolder = `${rootDir}/${year}`;
    const yearCreated = await ensureFolderExists(vault, yearFolder);
    if (!yearCreated) {
      return false;
    }
    const monthFolder = `${rootDir}/${year}/${month.toString().padStart(2, "0")}`;
    const monthCreated = await ensureFolderExists(vault, monthFolder);
    if (!monthCreated) {
      return false;
    }
    return true;
  } catch (error) {
    console.error("Error ensuring daily folder structure:", error);
    return false;
  }
}
function escapeRegExp(str) {
  return str.replace(/[.*+?^${}()|[\]\\-]/g, "\\$&");
}
function getYesterdayDate() {
  const today = new Date();
  const yesterday = new Date(today);
  yesterday.setDate(today.getDate() - 1);
  const year = yesterday.getFullYear();
  const month = (yesterday.getMonth() + 1).toString().padStart(2, "0");
  const day = yesterday.getDate().toString().padStart(2, "0");
  return `${year}-${month}-${day}`;
}
function getYesterdayTaskFilePath(rootDir, isWorkdayMode = false) {
  const yesterdayDate = isWorkdayMode ? getLastWorkdayDate(1) : getYesterdayDate();
  const yesterday = new Date(yesterdayDate);
  const year = yesterday.getFullYear().toString();
  const isEnglish = isEnglishEnvironment();
  const yesterdayMonth = yesterday.getMonth();
  const monthName = isEnglish ? getMonthNameEN(yesterdayMonth) : getMonthNameZH(yesterdayMonth);
  return (0, import_obsidian.normalizePath)(`${rootDir}/${year}/${monthName}.md`);
}
function getMonthNameZH(monthIndex) {
  const months = [
    "1\u6708",
    "2\u6708",
    "3\u6708",
    "4\u6708",
    "5\u6708",
    "6\u6708",
    "7\u6708",
    "8\u6708",
    "9\u6708",
    "10\u6708",
    "11\u6708",
    "12\u6708"
  ];
  return months[monthIndex];
}
function getMonthNameEN(monthIndex) {
  const months = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December"
  ];
  return months[monthIndex];
}
async function extractTasksForDate(vault, filePath, date) {
  try {
    const abstractFile = vault.getAbstractFileByPath(filePath);
    if (!abstractFile || !(abstractFile instanceof import_obsidian.TFile)) {
      console.log(`[DEBUG] \u63D0\u53D6\u4EFB\u52A1 - \u6587\u4EF6\u4E0D\u5B58\u5728: ${filePath}`);
      return null;
    }
    const content = await vault.read(abstractFile);
    const escapedDate = escapeRegExp(date);
    const dateRegexes = [
      // 主要格式：一级标题 + 任意内容 + 日期 + 任意内容
      new RegExp(`^# [^\\r\\n]*${escapedDate}[^\\r\\n]*$`, "m"),
      // 向后兼容：二级标题格式
      new RegExp(`^## [^\\r\\n]*${escapedDate}[^\\r\\n]*$`, "m")
    ];
    let match = null;
    let usedRegexIndex = -1;
    for (let i = 0; i < dateRegexes.length; i++) {
      match = content.match(dateRegexes[i]);
      if (match) {
        usedRegexIndex = i;
        break;
      }
    }
    if (!match || match.index === void 0) {
      console.log(`[DEBUG] \u63D0\u53D6\u4EFB\u52A1 - \u672A\u627E\u5230\u65E5\u671F\u6807\u9898: ${date} in ${filePath}`);
      console.log(`[DEBUG] \u641C\u7D22\u7684\u65E5\u671F: ${escapedDate}`);
      console.log(`[DEBUG] \u4F7F\u7528\u7684\u6B63\u5219\u8868\u8FBE\u5F0F:`);
      dateRegexes.forEach((regex, index) => {
        console.log(`  ${index + 1}. ${regex.source}`);
      });
      console.log(`[DEBUG] \u6587\u4EF6\u5185\u5BB9\u9884\u89C8: ${content.substring(0, 500)}...`);
      return null;
    }
    console.log(`[DEBUG] \u627E\u5230\u65E5\u671F\u6807\u9898\uFF0C\u4F7F\u7528\u6B63\u5219 ${usedRegexIndex + 1}: ${match[0]}`);
    const startPos = match.index;
    const remainingContent = content.slice(startPos + match[0].length);
    console.log(`[DEBUG] \u5269\u4F59\u5185\u5BB9\u957F\u5EA6: ${remainingContent.length}`);
    const nextDatePatterns = [
      // 一级标题 + 必须包含完整日期格式 YYYY-MM-DD
      /\n# [^\\r\\n]*\d{4}-\d{2}-\d{2}[^\\r\\n]*/,
      // 二级标题 + 必须包含完整日期格式 YYYY-MM-DD  
      /\n## [^\\r\\n]*\d{4}-\d{2}-\d{2}[^\\r\\n]*/
    ];
    let nextHeadingPos = -1;
    let foundNextDateTitle = "";
    for (const pattern of nextDatePatterns) {
      const nextMatch = remainingContent.match(pattern);
      if (nextMatch && nextMatch.index !== void 0) {
        const matchedLine = nextMatch[0].trim();
        console.log(`[DEBUG] \u68C0\u67E5\u53EF\u80FD\u7684\u4E0B\u4E00\u4E2A\u65E5\u671F\u6807\u9898: "${matchedLine}"`);
        const firstLine = matchedLine.split("\n")[0];
        console.log(`[DEBUG] \u63D0\u53D6\u7684\u6807\u9898\u884C: "${firstLine}"`);
        if (/\d{4}-\d{2}-\d{2}/.test(firstLine)) {
          nextHeadingPos = nextMatch.index;
          foundNextDateTitle = firstLine;
          console.log(`[DEBUG] \u786E\u8BA4\u627E\u5230\u4E0B\u4E00\u4E2A\u65E5\u671F\u6807\u9898\uFF0C\u4F4D\u7F6E: ${nextHeadingPos}, \u5185\u5BB9: ${foundNextDateTitle}`);
          break;
        } else {
          console.log(`[DEBUG] \u8DF3\u8FC7\u975E\u65E5\u671F\u6807\u9898: "${firstLine}"`);
        }
      }
    }
    let endPos;
    if (nextHeadingPos !== -1) {
      endPos = startPos + match[0].length + nextHeadingPos;
      console.log(`[DEBUG] \u4F7F\u7528\u4E0B\u4E00\u4E2A\u65E5\u671F\u6807\u9898\u4F5C\u4E3A\u7ED3\u675F\u4F4D\u7F6E: ${endPos}`);
    } else {
      endPos = content.length;
      console.log(`[DEBUG] \u672A\u627E\u5230\u4E0B\u4E00\u4E2A\u65E5\u671F\u6807\u9898\uFF0C\u63D0\u53D6\u5230\u6587\u4EF6\u672B\u5C3E`);
    }
    const extractedContent = content.slice(startPos, endPos).trim();
    console.log(`[DEBUG] \u63D0\u53D6\u4EFB\u52A1\u6210\u529F: ${date}`);
    console.log(`[DEBUG] \u63D0\u53D6\u5185\u5BB9\u957F\u5EA6: ${extractedContent.length} \u5B57\u7B26`);
    console.log(`[DEBUG] \u63D0\u53D6\u5185\u5BB9\u9884\u89C8: ${extractedContent.substring(0, 200)}...`);
    console.log(`[DEBUG] \u63D0\u53D6\u5185\u5BB9\u5B8C\u6574: ${extractedContent}`);
    return extractedContent;
  } catch (error) {
    console.error(`Error extracting tasks for date ${date}:`, error);
    return null;
  }
}
function analyzeTaskCompletion(taskContent) {
  const result = {
    totalTasks: 0,
    completedTasks: 0,
    unfinishedTasksList: []
  };
  if (!taskContent) {
    console.log(`[DEBUG] \u4EFB\u52A1\u5206\u6790 - \u5185\u5BB9\u4E3A\u7A7A`);
    return result;
  }
  console.log(`[DEBUG] \u4EFB\u52A1\u5206\u6790 - \u5F00\u59CB\u5206\u6790\u5185\u5BB9\uFF0C\u957F\u5EA6: ${taskContent.length}`);
  console.log(`[DEBUG] \u4EFB\u52A1\u5206\u6790 - \u5185\u5BB9\u9884\u89C8:
${taskContent}`);
  const allTasksRegex = /^[\s]*-[\s]*\[([ xX✓])\][\s]+(.+)$/gm;
  const completedTasksRegex = /^[\s]*-[\s]*\[([xX✓])\][\s]+(.+)$/gm;
  const unfinishedTasksRegex = /^[\s]*-[\s]*\[[\s]\][\s]+(.+)$/gm;
  const allTasksMatches = [...taskContent.matchAll(allTasksRegex)];
  result.totalTasks = allTasksMatches.length;
  const completedTasksMatches = [...taskContent.matchAll(completedTasksRegex)];
  result.completedTasks = completedTasksMatches.length;
  const unfinishedTasksMatches = [...taskContent.matchAll(unfinishedTasksRegex)];
  result.unfinishedTasksList = unfinishedTasksMatches.map((match) => {
    let taskText = match[1].trim();
    taskText = taskText.replace(/\s*✅\s*\d{4}-\d{2}-\d{2}.*$/, "");
    return taskText;
  });
  console.log(`[DEBUG] \u4EFB\u52A1\u5206\u6790\u7ED3\u679C:`);
  console.log(`  - \u603B\u4EFB\u52A1\u5339\u914D: ${allTasksMatches.length}`);
  console.log(`  - \u5DF2\u5B8C\u6210\u5339\u914D: ${completedTasksMatches.length}`);
  console.log(`  - \u672A\u5B8C\u6210\u5339\u914D: ${unfinishedTasksMatches.length}`);
  console.log(`  - \u672A\u5B8C\u6210\u4EFB\u52A1\u5217\u8868: ${result.unfinishedTasksList.slice(0, 3).join(", ")}${result.unfinishedTasksList.length > 3 ? "..." : ""}`);
  const taskLines = taskContent.split("\n").filter((line) => line.includes("- ["));
  console.log(`[DEBUG] \u627E\u5230\u7684\u4EFB\u52A1\u884C\u793A\u4F8B (\u5171${taskLines.length}\u884C):`);
  taskLines.slice(0, 10).forEach((line, index) => {
    console.log(`  ${index + 1}. "${line}"`);
  });
  if (taskLines.length === 0) {
    console.log(`[DEBUG] \u672A\u627E\u5230\u4EFB\u52A1\u884C\uFF0C\u8F93\u51FA\u6240\u6709\u5185\u5BB9\u884C:`);
    const allLines = taskContent.split("\n");
    allLines.slice(0, 20).forEach((line, index) => {
      console.log(`  ${index + 1}. "${line}"`);
    });
  }
  return result;
}
function generateStatisticsContent(tasks, t, maxSuggestions = 5) {
  let totalTasks;
  let completedTasks;
  let unfinishedTasks = [];
  if (Array.isArray(tasks)) {
    totalTasks = tasks.length;
    completedTasks = tasks.filter((task) => task.isCompleted).length;
    unfinishedTasks = tasks.filter((task) => !task.isCompleted).map((task) => ({ task: task.task }));
  } else {
    totalTasks = tasks.totalTasks;
    completedTasks = tasks.completedTasks;
    unfinishedTasks = tasks.unfinishedTasksList.map((task) => ({ task }));
  }
  const completionRate = totalTasks > 0 ? Math.round(completedTasks / totalTasks * 100) : 0;
  const displayTasks = unfinishedTasks.slice(0, maxSuggestions);
  let content = `## ${t("statistics.title")}
---
`;
  content += `- ${t("statistics.totalTasks")}: ${totalTasks}
`;
  content += `- ${t("statistics.completedTasks")}: ${completedTasks}
`;
  content += `- ${t("statistics.completionRate")}: ${completionRate}%

`;
  if (unfinishedTasks.length > 0) {
    content += `### ${t("statistics.suggestions")}
---
`;
    displayTasks.forEach((item) => {
      content += `- [ ] ${item.task}
`;
    });
    if (unfinishedTasks.length > maxSuggestions) {
      const remaining = unfinishedTasks.length - maxSuggestions;
      const moreTasks = remaining === 1 ? t("statistics.moreTasks.singular") : `${remaining} ${t("statistics.moreTasks.plural")}`;
      content += `- *${moreTasks}*
`;
    }
  }
  return content;
}
async function readDailyTaskFile(vault, filePath) {
  try {
    const abstractFile = vault.getAbstractFileByPath(filePath);
    if (!abstractFile || !(abstractFile instanceof import_obsidian.TFile)) {
      return null;
    }
    const content = await vault.read(abstractFile);
    return content;
  } catch (error) {
    console.error(`Error reading daily task file: ${filePath}`, error);
    return null;
  }
}

// src/taskGenerator.ts
var TaskGenerator = class {
  constructor(app, settingsManager) {
    this.app = app;
    this.vault = app.vault;
    this.settingsManager = settingsManager;
  }
  /**
   * 生成每日任务
   * @param openFile 是否打开文件
   * @param quietMode 静默模式，减少日志输出
   * @returns 成功或失败
   */
  async generateDailyTask(openFile = true, quietMode = false) {
    try {
      const settings = this.settingsManager.getSettings();
      const rootDir = settings.rootDir.trim() || "DailyTasks";
      if (settings.fileGenerationMode === "daily") {
        return await this.generateDailyTaskFile(rootDir, settings.dailyFilePrefix, openFile, quietMode);
      } else {
        return await this.generateMonthlyTaskFile(rootDir, openFile, quietMode);
      }
    } catch (error) {
      console.error("Error generating daily task:", error);
      const errorMsg = error instanceof Error ? error.message : String(error);
      this.showErrorNotice(`${getTranslation("notification.error")} ${errorMsg}`);
      return false;
    }
  }
  /**
   * 生成日度任务文件（每日独立文件）
   * @param rootDir 根目录
   * @param filePrefix 文件前缀
   * @param openFile 是否打开文件
   * @param quietMode 静默模式
   * @returns 成功或失败
   */
  async generateDailyTaskFile(rootDir, filePrefix, openFile, quietMode) {
    const filePath = getDailyTaskFilePath(rootDir, filePrefix);
    const abstractFile = this.vault.getAbstractFileByPath(filePath);
    if (abstractFile && abstractFile instanceof import_obsidian2.TFile) {
      if (!quietMode)
        console.log(`\u4ECA\u65E5\u4EFB\u52A1\u6587\u4EF6\u5DF2\u5B58\u5728\uFF0C\u8DF3\u8FC7\u521B\u5EFA: ${filePath}`);
      if (openFile) {
        this.showWarningNotice(`\u{1F4CC} ${getTranslation("notification.fileExists")}`);
        const leaf = this.app.workspace.getLeaf();
        await leaf.openFile(abstractFile);
      }
      return true;
    }
    const folderCreated = await ensureDailyFolderStructure(this.vault, rootDir, filePrefix);
    if (!folderCreated) {
      throw new Error(`\u65E0\u6CD5\u521B\u5EFA\u76EE\u5F55\u7ED3\u6784: ${rootDir}`);
    }
    let statisticsContent = "";
    const settings = this.settingsManager.getSettings();
    if (settings.taskStatistics) {
      const date = getCurrentDate();
      statisticsContent = await this.generateYesterdayStatistics(rootDir, date, quietMode);
    }
    const template = this.getTaskTemplate();
    const renderedContent = renderTemplate(template);
    const fullContent = statisticsContent ? `${statisticsContent}

${renderedContent}` : renderedContent;
    const fileCreated = await ensureFileExists(this.vault, filePath, fullContent);
    if (!fileCreated) {
      throw new Error(`\u65E0\u6CD5\u521B\u5EFA\u4EFB\u52A1\u6587\u4EF6: ${filePath}`);
    }
    if (!quietMode)
      console.log(`\u2705 \u65E5\u5EA6\u4EFB\u52A1\u6587\u4EF6\u521B\u5EFA\u6210\u529F: ${filePath}`);
    if (openFile) {
      const createdFile = this.vault.getAbstractFileByPath(filePath);
      if (createdFile && createdFile instanceof import_obsidian2.TFile) {
        const leaf = this.app.workspace.getLeaf();
        await leaf.openFile(createdFile);
        setTimeout(() => {
          this.showSuccessNotice(`\u2728 ${getTranslation("notification.taskAdded")}`);
        }, 300);
      }
    }
    return true;
  }
  /**
   * 转义正则表达式中的特殊字符
   * @param str 需要转义的字符串
   * @returns 转义后的字符串
   */
  escapeRegExp(str) {
    return str.replace(/[.*+?^${}()|[\]\\-]/g, "\\$&");
  }
  /**
   * 生成月度任务文件（追加到月份文件）
   * @param rootDir 根目录
   * @param openFile 是否打开文件
   * @param quietMode 静默模式
   * @returns 成功或失败
   */
  async generateMonthlyTaskFile(rootDir, openFile, quietMode) {
    const filePath = getTaskFilePath(rootDir);
    const pathParts = filePath.split("/");
    const year = pathParts.length > 1 ? pathParts[1] : "";
    const monthName = pathParts.length > 2 ? pathParts[2].replace(".md", "") : "";
    const yearFolder = `${rootDir}/${year}`;
    const rootCreated = await ensureFolderExists(this.vault, rootDir);
    if (!rootCreated) {
      throw new Error(`\u65E0\u6CD5\u8BBF\u95EE\u6839\u76EE\u5F55: ${rootDir}\uFF0C\u53EF\u80FD\u662F\u5B58\u5728\u540C\u540D\u6587\u4EF6\u6216\u6743\u9650\u95EE\u9898`);
    }
    const yearCreated = await ensureFolderExists(this.vault, yearFolder);
    if (!yearCreated) {
      throw new Error(`\u65E0\u6CD5\u8BBF\u95EE\u5E74\u4EFD\u76EE\u5F55: ${yearFolder}\uFF0C\u53EF\u80FD\u662F\u5B58\u5728\u540C\u540D\u6587\u4EF6\u6216\u6743\u9650\u95EE\u9898`);
    }
    const fileCreated = await ensureFileExists(this.vault, filePath);
    if (!fileCreated) {
      throw new Error(`\u65E0\u6CD5\u8BBF\u95EE\u6708\u4EFD\u6587\u4EF6: ${filePath}\uFF0C\u8BF7\u68C0\u67E5\u662F\u5426\u5B58\u5728\u540C\u540D\u76EE\u5F55\u6216\u6743\u9650\u95EE\u9898`);
    }
    const date = getCurrentDate();
    const abstractFile = this.vault.getAbstractFileByPath(filePath);
    if (!abstractFile || !(abstractFile instanceof import_obsidian2.TFile)) {
      throw new Error(`\u627E\u4E0D\u5230\u6709\u6548\u7684\u6587\u4EF6: ${filePath}`);
    }
    const fileContent = await this.vault.read(abstractFile);
    const escapedDate = this.escapeRegExp(date);
    const dateRegexes = [
      // 主要格式：一级标题 + 日期 + 竖线分隔符
      new RegExp(`^# [^\\r\\n]*${escapedDate}[^\\r\\n]*\\|[^\\r\\n]*$`, "m"),
      // 兼容格式：一级标题 + 日期（不带竖线）
      new RegExp(`^# [^\\r\\n]*${escapedDate}[^\\r\\n]*$`, "m"),
      // 向后兼容：二级标题格式（旧版本可能存在）
      new RegExp(`^## [^\\r\\n]*${escapedDate}[^\\r\\n]*$`, "m")
    ];
    const existingTaskCheck = dateRegexes.some((regex) => regex.test(fileContent));
    if (!quietMode) {
      console.log(`[DEBUG] \u6708\u5EA6\u6A21\u5F0F\u4EFB\u52A1\u91CD\u590D\u68C0\u67E5:`);
      console.log(`  - \u65E5\u671F: ${date}`);
      console.log(`  - \u8F6C\u4E49\u540E: ${escapedDate}`);
      console.log(`  - \u6587\u4EF6\u8DEF\u5F84: ${filePath}`);
      console.log(`  - \u68C0\u67E5\u7684\u6B63\u5219\u8868\u8FBE\u5F0F:`);
      dateRegexes.forEach((regex, index) => {
        console.log(`    ${index + 1}. ${regex.source}`);
      });
      console.log(`  - \u68C0\u67E5\u7ED3\u679C: ${existingTaskCheck}`);
    }
    if (existingTaskCheck) {
      if (!quietMode)
        console.log(`\u4ECA\u65E5(${date})\u4EFB\u52A1\u5DF2\u5B58\u5728\u4E8E\u6587\u4EF6\u4E2D\uFF0C\u8DF3\u8FC7\u521B\u5EFA`);
      if (openFile) {
        this.showWarningNotice(`\u{1F4CC} ${getTranslation("notification.taskExists")}`);
        const leaf = this.app.workspace.getLeaf();
        await leaf.openFile(abstractFile);
      }
      return true;
    }
    let statisticsContent = "";
    if (this.settingsManager.getSettings().taskStatistics) {
      statisticsContent = await this.generateYesterdayStatistics(rootDir, date, quietMode);
    }
    const template = this.getTaskTemplate();
    const renderedContent = renderTemplate(template);
    const fullContent = statisticsContent ? `${statisticsContent}

${renderedContent}` : renderedContent;
    const success = await appendToFile(this.vault, filePath, fullContent);
    if (success) {
      if (!quietMode)
        console.log(`\u2705 \u4EFB\u52A1\u5185\u5BB9\u8FFD\u52A0\u6210\u529F ${date}`);
      if (openFile) {
        const leaf = this.app.workspace.getLeaf();
        await leaf.openFile(abstractFile);
        setTimeout(() => {
          this.showSuccessNotice(`\u2728 ${getTranslation("notification.taskAdded")}`);
        }, 300);
      }
    } else {
      throw new Error(`\u65E0\u6CD5\u5411\u6587\u4EF6\u8FFD\u52A0\u5185\u5BB9: ${filePath}`);
    }
    return success;
  }
  /**
   * 获取任务模板
   * @returns 任务模板内容
   */
  getTaskTemplate() {
    if (this.settingsManager.hasCustomTemplate()) {
      return this.settingsManager.getSettings().customTemplate;
    } else {
      return this.settingsManager.getTemplateByLanguage();
    }
  }
  /**
   * 生成昨日任务统计信息
   * @param rootDir 根目录
   * @param todayDate 今日日期
   * @param quietMode 静默模式
   * @returns 统计信息内容或空字符串
   */
  async generateYesterdayStatistics(rootDir, todayDate, quietMode = false) {
    try {
      const settings = this.settingsManager.getSettings();
      const isWorkdayMode = settings.autoGenerateMode === "workday" /* WORKDAY */;
      const isDailyFileMode = settings.fileGenerationMode === "daily";
      const yesterdayDate = isWorkdayMode ? getLastWorkdayDate(1) : getYesterdayDate();
      console.log(`[\u7EDF\u8BA1] \u5F00\u59CB\u751F\u6210\u6628\u65E5\u4EFB\u52A1\u7EDF\u8BA1:`);
      console.log(`  - \u4ECA\u65E5\u65E5\u671F: ${todayDate}`);
      console.log(`  - \u524D\u4E00\u5929\u65E5\u671F: ${yesterdayDate}`);
      console.log(`  - \u6587\u4EF6\u751F\u6210\u6A21\u5F0F: ${isDailyFileMode ? "\u65E5\u5EA6" : "\u6708\u5EA6"}`);
      console.log(`  - \u81EA\u52A8\u751F\u6210\u6A21\u5F0F: ${isWorkdayMode ? "\u5DE5\u4F5C\u65E5" : "\u6BCF\u65E5"}`);
      console.log(`  - \u9759\u9ED8\u6A21\u5F0F: ${quietMode}`);
      let yesterdayContent = null;
      let yesterdayFilePath = "";
      if (isDailyFileMode) {
        yesterdayFilePath = getYesterdayDailyTaskFilePath(rootDir, settings.dailyFilePrefix, isWorkdayMode);
        console.log(`[\u7EDF\u8BA1] \u65E5\u5EA6\u6A21\u5F0F - \u6628\u65E5\u6587\u4EF6\u8DEF\u5F84: ${yesterdayFilePath}`);
        yesterdayContent = await readDailyTaskFile(this.vault, yesterdayFilePath);
      } else {
        yesterdayFilePath = getYesterdayTaskFilePath(rootDir, isWorkdayMode);
        console.log(`[\u7EDF\u8BA1] \u6708\u5EA6\u6A21\u5F0F - \u6628\u65E5\u6587\u4EF6\u8DEF\u5F84: ${yesterdayFilePath}`);
        yesterdayContent = await extractTasksForDate(this.vault, yesterdayFilePath, yesterdayDate);
      }
      if (!yesterdayContent || yesterdayContent.trim() === "") {
        console.log(`[\u7EDF\u8BA1] \u672A\u627E\u5230\u524D\u4E00\u5929(${yesterdayDate})\u7684\u4EFB\u52A1\u5185\u5BB9\uFF0C\u8DF3\u8FC7\u7EDF\u8BA1`);
        console.log(`[\u7EDF\u8BA1] \u68C0\u67E5\u7684\u6587\u4EF6\u8DEF\u5F84: ${yesterdayFilePath}`);
        return "";
      }
      console.log(`[\u7EDF\u8BA1] \u627E\u5230\u524D\u4E00\u5929\u4EFB\u52A1\u5185\u5BB9\uFF0C\u957F\u5EA6: ${yesterdayContent.length} \u5B57\u7B26`);
      const taskStats = analyzeTaskCompletion(yesterdayContent);
      console.log(`[\u7EDF\u8BA1] \u524D\u4E00\u5929\u4EFB\u52A1\u5206\u6790\u7ED3\u679C:`);
      console.log(`  - \u603B\u4EFB\u52A1\u6570: ${taskStats.totalTasks}`);
      console.log(`  - \u5DF2\u5B8C\u6210: ${taskStats.completedTasks}`);
      console.log(`  - \u672A\u5B8C\u6210: ${taskStats.unfinishedTasksList.length}`);
      console.log(`  - \u5B8C\u6210\u7387: ${taskStats.totalTasks > 0 ? Math.round(taskStats.completedTasks / taskStats.totalTasks * 100) : 0}%`);
      if (taskStats.totalTasks === 0) {
        console.log(`[\u7EDF\u8BA1] \u524D\u4E00\u5929\u6CA1\u6709\u4EFB\u52A1\uFF0C\u8DF3\u8FC7\u7EDF\u8BA1\u751F\u6210`);
        return "";
      }
      const statisticsContent = generateStatisticsContent(taskStats, getTranslation, settings.statisticsMaxSuggestions);
      console.log(`[\u7EDF\u8BA1] \u7EDF\u8BA1\u5185\u5BB9\u751F\u6210\u6210\u529F\uFF0C\u957F\u5EA6: ${statisticsContent.length} \u5B57\u7B26`);
      console.log(`[\u7EDF\u8BA1] \u5C06\u5728\u4ECA\u65E5\u4EFB\u52A1\u524D\u6DFB\u52A0\u7EDF\u8BA1\u4FE1\u606F`);
      return statisticsContent;
    } catch (error) {
      console.error("[\u7EDF\u8BA1] \u751F\u6210\u6628\u65E5\u7EDF\u8BA1\u65F6\u53D1\u751F\u9519\u8BEF:", error);
      console.error("[\u7EDF\u8BA1] \u9519\u8BEF\u8BE6\u60C5:", error.message || error);
      return "";
    }
  }
  /**
   * 手动添加任务（从命令面板或图标调用）
   * @returns 成功或失败
   */
  async addTaskManually() {
    try {
      this.showWarningNotice(`\u23F3 ${getTranslation("notification.generating")}`);
      return await this.generateDailyTask(true);
    } catch (error) {
      console.error("\u624B\u52A8\u6DFB\u52A0\u4EFB\u52A1\u5931\u8D25:", error);
      const errorMsg = error instanceof Error ? error.message : String(error);
      this.showErrorNotice(`${getTranslation("notification.error")} ${errorMsg}`);
      return false;
    }
  }
  /**
   * 显示成功通知
   */
  showSuccessNotice(message) {
    new import_obsidian2.Notice(message, 4e3);
  }
  /**
   * 显示警告通知
   */
  showWarningNotice(message) {
    new import_obsidian2.Notice(message, 3e3);
  }
  /**
   * 显示错误通知
   */
  showErrorNotice(message) {
    new import_obsidian2.Notice(message, 5e3);
  }
};

// src/settings/settings.ts
var TextCenterCSS = "daily-task-text-center";
var SaveIndicatorCSS = "daily-task-save-indicator";
var SuccessIconCSS = "daily-task-success-icon";
var SettingTopSpaceCSS = "daily-task-setting-top-space";
var InputContainerCSS = "daily-task-input-container";
var InputCSS = "daily-task-input";
var DailyTaskSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.previewEl = null;
    this.addTaskButton = null;
    // 目录输入框
    this.rootDirInput = null;
    // 标记设置是否已修改但未保存
    this.dirtySettings = false;
    this.plugin = plugin;
    this.settingsManager = plugin.settingsManager;
    this.taskGenerator = new TaskGenerator(app, this.settingsManager);
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.classList.add("daily-task-setting-tab");
    const settings = this.settingsManager.getSettings();
    const topSpacing = containerEl.createEl("div");
    topSpacing.classList.add(SettingTopSpaceCSS);
    const rootDirSetting = new import_obsidian3.Setting(containerEl).setName(getTranslation("settings.rootDir")).setDesc(getTranslation("settings.rootDir.desc"));
    const inputContainer = document.createElement("div");
    inputContainer.classList.add(InputContainerCSS);
    rootDirSetting.controlEl.appendChild(inputContainer);
    this.rootDirInput = new import_obsidian3.TextComponent(inputContainer).setValue(settings.rootDir).onChange(async (value) => {
      if (value.trim() !== "") {
        this.dirtySettings = true;
        this.autoSaveRootDir(value);
      }
    });
    if (this.rootDirInput && this.rootDirInput.inputEl) {
      this.rootDirInput.inputEl.classList.add(InputCSS);
      this.rootDirInput.inputEl.placeholder = "DailyTasks";
    }
    const saveIndicator = document.createElement("div");
    saveIndicator.classList.add(SaveIndicatorCSS);
    inputContainer.appendChild(saveIndicator);
    const saveSuccessIcon = createSpan({ cls: `svg-icon lucide-check ${SuccessIconCSS}` });
    saveIndicator.appendChild(saveSuccessIcon);
    let autoSaveTimer = null;
    this.autoSaveRootDir = async (value) => {
      if (autoSaveTimer !== null) {
        clearTimeout(autoSaveTimer);
      }
      autoSaveTimer = setTimeout(async () => {
        let pathToSave = value.trim();
        if (pathToSave === "") {
          pathToSave = "DailyTasks";
        }
        await this.settingsManager.updateSettings({ rootDir: pathToSave });
        this.dirtySettings = false;
        saveIndicator.style.opacity = "1";
        setTimeout(() => {
          saveIndicator.style.opacity = "0";
        }, 1500);
      }, 800);
    };
    const autoGenSetting = new import_obsidian3.Setting(containerEl).setName(getTranslation("settings.autoGenerate")).setDesc(getTranslation("settings.autoGenerate.desc"));
    const toggleContainer = document.createElement("div");
    toggleContainer.classList.add("mode-toggle-container");
    toggleContainer.style.width = "20%";
    toggleContainer.style.marginLeft = "auto";
    const modes = [
      { value: "none" /* NONE */, label: getTranslation("settings.mode.none") },
      { value: "daily" /* DAILY */, label: getTranslation("settings.mode.daily") },
      { value: "workday" /* WORKDAY */, label: getTranslation("settings.mode.workday") }
    ];
    const slider = document.createElement("div");
    slider.classList.add("mode-toggle-slider");
    toggleContainer.appendChild(slider);
    const updateSlider = (index) => {
      slider.style.left = `${index * 33.33}%`;
    };
    let currentModeIndex = modes.findIndex((mode) => mode.value === settings.autoGenerateMode);
    if (currentModeIndex === -1) {
      currentModeIndex = modes.findIndex((mode) => mode.value === "workday" /* WORKDAY */);
      this.settingsManager.updateSettings({ autoGenerateMode: "workday" /* WORKDAY */ });
    }
    updateSlider(currentModeIndex);
    modes.forEach((mode, index) => {
      const option = document.createElement("div");
      option.classList.add("mode-toggle-option");
      option.textContent = mode.label;
      if (mode.value === settings.autoGenerateMode) {
        option.classList.add("active");
      }
      option.addEventListener("click", async () => {
        toggleContainer.querySelectorAll(".mode-toggle-option").forEach((el) => {
          el.classList.remove("active");
        });
        option.classList.add("active");
        updateSlider(index);
        await this.settingsManager.updateSettings({ autoGenerateMode: mode.value });
      });
      toggleContainer.appendChild(option);
    });
    autoGenSetting.controlEl.appendChild(toggleContainer);
    const fileGenModeSetting = new import_obsidian3.Setting(containerEl).setName(getTranslation("settings.fileGenerationMode")).setDesc(getTranslation("settings.fileGenerationMode.desc"));
    const fileGenModeDropdown = new import_obsidian3.DropdownComponent(fileGenModeSetting.controlEl).addOption("monthly", getTranslation("settings.fileMode.monthly")).addOption("daily", getTranslation("settings.fileMode.daily")).setValue(settings.fileGenerationMode).onChange(async (value) => {
      await this.settingsManager.updateSettings({ fileGenerationMode: value });
      this.display();
    });
    let dailyFilePrefixSetting = null;
    if (settings.fileGenerationMode === "daily") {
      dailyFilePrefixSetting = new import_obsidian3.Setting(containerEl).setName(getTranslation("settings.dailyFilePrefix")).setDesc(getTranslation("settings.dailyFilePrefix.desc"));
      const prefixInputContainer = document.createElement("div");
      prefixInputContainer.classList.add(InputContainerCSS);
      dailyFilePrefixSetting.controlEl.appendChild(prefixInputContainer);
      const prefixInput = new import_obsidian3.TextComponent(prefixInputContainer).setValue(settings.dailyFilePrefix).onChange(async (value) => {
        await this.settingsManager.updateSettings({ dailyFilePrefix: value });
      });
      if (prefixInput && prefixInput.inputEl) {
        prefixInput.inputEl.classList.add(InputCSS);
        prefixInput.inputEl.placeholder = getTranslation("settings.dailyFilePrefix.placeholder");
      }
    }
    new import_obsidian3.Setting(containerEl).setName(getTranslation("settings.language")).setDesc(getTranslation("settings.language.desc")).addDropdown((dropdown) => {
      dropdown.addOption("auto" /* AUTO */, getTranslation("settings.language.auto")).addOption("zh" /* ZH */, getTranslation("settings.language.zh")).addOption("en" /* EN */, getTranslation("settings.language.en")).setValue(settings.language).onChange(async (value) => {
        await this.settingsManager.updateSettings({ language: value });
        this.display();
      });
    });
    new import_obsidian3.Setting(containerEl).setName(getTranslation("settings.notificationDuration")).setDesc(getTranslation("settings.notificationDuration.desc")).addText((text) => {
      const component = text.setValue(settings.successNotificationDuration.toString()).onChange(async (value) => {
        const duration = parseInt(value);
        if (!isNaN(duration) && duration > 0) {
          await this.settingsManager.updateSettings({ successNotificationDuration: duration });
        }
      });
      component.inputEl.placeholder = "3000";
      return component;
    });
    new import_obsidian3.Setting(containerEl).setName(getTranslation("settings.taskStatistics")).setDesc(getTranslation("settings.taskStatistics.desc")).addToggle((toggle) => {
      const toggleEl = toggle.setValue(settings.taskStatistics).onChange(async (value) => {
        await this.settingsManager.updateSettings({ taskStatistics: value });
        this.display();
      });
      const toggleControl = toggle.toggleEl || toggle.containerEl.querySelector(".checkbox-container");
      if (toggleControl) {
        toggleControl.classList.add("task-statistics-toggle");
        const toggleContainer2 = toggleControl.parentElement;
        if (toggleContainer2) {
          const iconEl = createSpan({ cls: "svg-icon lucide-bar-chart-2" });
          iconEl.style.marginRight = "8px";
          iconEl.style.color = "var(--text-accent)";
          toggleContainer2.prepend(iconEl);
          toggleContainer2.style.transition = "all 0.3s ease";
          toggleControl.style.transition = "all 0.3s ease";
        }
      }
      return toggleEl;
    });
    if (settings.taskStatistics) {
      new import_obsidian3.Setting(containerEl).setName(getTranslation("settings.statisticsMaxSuggestions")).setDesc(getTranslation("settings.statisticsMaxSuggestions.desc")).addText((text) => {
        const component = text.setValue(settings.statisticsMaxSuggestions.toString()).onChange(async (value) => {
          const maxSuggestions = parseInt(value);
          if (!isNaN(maxSuggestions) && maxSuggestions > 0 && maxSuggestions <= 20) {
            await this.settingsManager.updateSettings({ statisticsMaxSuggestions: maxSuggestions });
          }
        });
        component.inputEl.placeholder = "5";
        component.inputEl.style.width = "60px";
        component.inputEl.style.textAlign = "center";
        return component;
      }).setClass("statistics-sub-setting");
      new import_obsidian3.Setting(containerEl).setName(getTranslation("settings.statisticsIncludeWeekends")).setDesc(getTranslation("settings.statisticsIncludeWeekends.desc")).addToggle((toggle) => {
        toggle.setValue(settings.statisticsIncludeWeekends).onChange(async (value) => {
          await this.settingsManager.updateSettings({ statisticsIncludeWeekends: value });
        });
      }).setClass("statistics-sub-setting");
    }
    containerEl.createEl("h3", { text: getTranslation("settings.template") });
    const templateDescription = containerEl.createEl("p", {
      text: this.settingsManager.getCurrentLanguage() === "zh" ? "\u6CE8\u610F\uFF1A\u9ED8\u8BA4\u6A21\u677F\u4F1A\u6839\u636E\u5F53\u524D\u8BED\u8A00\u73AF\u5883\u81EA\u52A8\u9009\u62E9\u5BF9\u5E94\u8BED\u8A00\u7684\u5185\u5BB9\u3002\u5982\u679C\u60A8\u81EA\u5B9A\u4E49\u6A21\u677F\uFF0C\u5C06\u5728\u6240\u6709\u8BED\u8A00\u73AF\u5883\u4E2D\u4F7F\u7528\u60A8\u7684\u81EA\u5B9A\u4E49\u5185\u5BB9\u3002" : "Note: Default template automatically adapts to your language environment. If you customize the template, your content will be used in all language environments."
    });
    templateDescription.style.fontSize = "0.85em";
    templateDescription.style.opacity = "0.8";
    templateDescription.style.marginBottom = "15px";
    const templateVariablesEl = containerEl.createEl("p");
    const variablesText = this.settingsManager.getCurrentLanguage() === "zh" ? "\u53EF\u7528\u53D8\u91CF\uFF1A" : "Available variables:";
    const variables = this.settingsManager.getCurrentLanguage() === "zh" ? [
      "{{date}} - \u65E5\u671F",
      "{{dateWithIcon}} - \u5E26\u56FE\u6807\u7684\u65E5\u671F",
      "{{weekday}} - \u661F\u671F\u51E0",
      "{{yearProgress}} - \u5E74\u8FDB\u5EA6",
      "{{monthProgress}} - \u6708\u8FDB\u5EA6",
      "{{time}} - \u5F53\u524D\u65F6\u95F4"
    ] : [
      "{{date}} - Date",
      "{{dateWithIcon}} - Date with icon",
      "{{weekday}} - Day of week",
      "{{yearProgress}} - Year progress",
      "{{monthProgress}} - Month progress",
      "{{time}} - Current time"
    ];
    const strongEl = templateVariablesEl.createEl("strong");
    strongEl.textContent = variablesText;
    templateVariablesEl.appendText(" " + variables.join(", "));
    templateVariablesEl.style.fontSize = "0.85em";
    templateVariablesEl.style.marginBottom = "10px";
    const templateSetting = new import_obsidian3.Setting(containerEl).setName(getTranslation("settings.template")).setClass("template-setting");
    const templateContainer = document.createElement("div");
    templateContainer.style.width = "100%";
    const currentTemplate = this.settingsManager.hasCustomTemplate() ? this.settingsManager.getSettings().customTemplate : this.settingsManager.getTemplateByLanguage();
    const textarea = new import_obsidian3.TextAreaComponent(templateContainer).setValue(currentTemplate).setPlaceholder(this.settingsManager.getCurrentLanguage() === "zh" ? "\u5728\u6B64\u5904\u8F93\u5165\u4EFB\u52A1\u6A21\u677F..." : "Enter task template here...").onChange(async (value) => {
      await this.settingsManager.updateSettings({
        customTemplate: value,
        hasCustomTemplate: true
      });
      this.updatePreview(this.previewEl, value);
    });
    textarea.inputEl.classList.add("template-editor");
    textarea.inputEl.style.height = "200px";
    textarea.inputEl.style.border = "1px solid var(--background-modifier-border-hover)";
    textarea.inputEl.style.borderRadius = "4px";
    textarea.inputEl.style.padding = "12px";
    textarea.inputEl.style.lineHeight = "1.5";
    textarea.inputEl.style.fontSize = "14px";
    textarea.inputEl.style.fontFamily = "var(--font-monospace)";
    textarea.inputEl.style.transition = "all 0.2s ease";
    textarea.inputEl.style.boxShadow = "inset 0 1px 3px rgba(0, 0, 0, 0.1)";
    textarea.inputEl.style.backgroundColor = "var(--background-primary)";
    textarea.inputEl.style.color = "var(--text-normal)";
    textarea.inputEl.style.resize = "vertical";
    textarea.inputEl.addEventListener("focus", () => {
      textarea.inputEl.style.border = "1px solid var(--interactive-accent)";
      textarea.inputEl.style.boxShadow = "0 0 0 2px rgba(var(--interactive-accent-rgb), 0.2), inset 0 1px 3px rgba(0, 0, 0, 0.1)";
      textarea.inputEl.style.outline = "none";
    });
    textarea.inputEl.addEventListener("blur", () => {
      textarea.inputEl.style.border = "1px solid var(--background-modifier-border-hover)";
      textarea.inputEl.style.boxShadow = "inset 0 1px 3px rgba(0, 0, 0, 0.1)";
    });
    const previewHeader = document.createElement("div");
    previewHeader.classList.add("template-preview-header");
    previewHeader.style.display = "flex";
    previewHeader.style.justifyContent = "space-between";
    previewHeader.style.marginTop = "15px";
    previewHeader.style.marginBottom = "10px";
    previewHeader.style.width = "100%";
    const previewBtnContainer = document.createElement("div");
    previewBtnContainer.style.display = "flex";
    previewBtnContainer.style.alignItems = "center";
    const resetBtnContainer = document.createElement("div");
    resetBtnContainer.style.display = "flex";
    resetBtnContainer.style.alignItems = "center";
    const toggleButton = new import_obsidian3.ButtonComponent(previewBtnContainer).setButtonText(getTranslation("settings.template.preview"));
    toggleButton.buttonEl.addClass(TextCenterCSS);
    toggleButton.buttonEl.style.textAlign = "center";
    toggleButton.buttonEl.style.display = "flex";
    toggleButton.buttonEl.style.alignItems = "center";
    toggleButton.buttonEl.style.justifyContent = "center";
    toggleButton.buttonEl.style.width = "130px";
    toggleButton.buttonEl.style.borderRadius = "4px";
    toggleButton.buttonEl.style.boxShadow = "0 2px 5px rgba(0,0,0,0.1)";
    toggleButton.buttonEl.style.transition = "all 0.2s ease";
    const eyeIcon = document.createElement("span");
    eyeIcon.classList.add("svg-icon");
    const eyeIconSvg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    eyeIconSvg.setAttribute("viewBox", "0 0 24 24");
    eyeIconSvg.setAttribute("fill", "none");
    eyeIconSvg.setAttribute("stroke", "currentColor");
    eyeIconSvg.setAttribute("stroke-width", "2");
    eyeIconSvg.setAttribute("stroke-linecap", "round");
    eyeIconSvg.setAttribute("stroke-linejoin", "round");
    const eyePath = document.createElementNS("http://www.w3.org/2000/svg", "path");
    eyePath.setAttribute("d", "M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z");
    const eyeCircle = document.createElementNS("http://www.w3.org/2000/svg", "circle");
    eyeCircle.setAttribute("cx", "12");
    eyeCircle.setAttribute("cy", "12");
    eyeCircle.setAttribute("r", "3");
    eyeIconSvg.appendChild(eyePath);
    eyeIconSvg.appendChild(eyeCircle);
    eyeIcon.appendChild(eyeIconSvg);
    eyeIcon.style.marginRight = "6px";
    toggleButton.buttonEl.prepend(eyeIcon);
    this.previewEl = document.createElement("div");
    this.previewEl.classList.add("template-preview");
    this.previewEl.style.marginTop = "15px";
    this.previewEl.style.padding = "15px";
    this.previewEl.style.border = "1px dashed var(--background-modifier-border)";
    this.previewEl.style.borderRadius = "8px";
    this.previewEl.style.backgroundColor = "var(--background-secondary)";
    this.previewEl.style.display = "none";
    this.previewEl.style.maxHeight = "200px";
    this.previewEl.style.overflow = "auto";
    this.previewEl.style.boxShadow = "inset 0 0 5px rgba(0,0,0,0.1)";
    this.updatePreview(this.previewEl, currentTemplate);
    templateContainer.appendChild(this.previewEl);
    toggleButton.onClick(() => {
      this.togglePreview(this.previewEl);
      if (this.previewEl && this.previewEl.classList.contains("visible")) {
        eyePath.setAttribute("d", "M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24");
        if (!eyeIconSvg.querySelector("line")) {
          const eyeLine = document.createElementNS("http://www.w3.org/2000/svg", "line");
          eyeLine.setAttribute("x1", "1");
          eyeLine.setAttribute("y1", "1");
          eyeLine.setAttribute("x2", "23");
          eyeLine.setAttribute("y2", "23");
          eyeIconSvg.appendChild(eyeLine);
        }
        toggleButton.setButtonText(getTranslation("settings.template.hide"));
        toggleButton.buttonEl.style.backgroundColor = "var(--background-modifier-success)";
      } else {
        eyePath.setAttribute("d", "M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z");
        const eyeLine = eyeIconSvg.querySelector("line");
        if (eyeLine) {
          eyeIconSvg.removeChild(eyeLine);
        }
        toggleButton.setButtonText(getTranslation("settings.template.preview"));
        toggleButton.buttonEl.style.backgroundColor = "";
      }
    });
    const resetTemplateBtn = new import_obsidian3.ButtonComponent(resetBtnContainer).setButtonText(getTranslation("settings.restoreTemplate"));
    resetTemplateBtn.buttonEl.classList.add(TextCenterCSS, "restore-template-button");
    const restoreIcon = document.createElement("span");
    restoreIcon.classList.add("svg-icon");
    const restoreIconSvg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    restoreIconSvg.setAttribute("viewBox", "0 0 24 24");
    restoreIconSvg.setAttribute("fill", "none");
    restoreIconSvg.setAttribute("stroke", "currentColor");
    restoreIconSvg.setAttribute("stroke-width", "2");
    restoreIconSvg.setAttribute("stroke-linecap", "round");
    restoreIconSvg.setAttribute("stroke-linejoin", "round");
    const path1 = document.createElementNS("http://www.w3.org/2000/svg", "path");
    path1.setAttribute("d", "M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z");
    const polyline1 = document.createElementNS("http://www.w3.org/2000/svg", "polyline");
    polyline1.setAttribute("points", "14 2 14 8 20 8");
    const path2 = document.createElementNS("http://www.w3.org/2000/svg", "path");
    path2.setAttribute("d", "M10 12l2 2 4-4");
    restoreIconSvg.appendChild(path1);
    restoreIconSvg.appendChild(polyline1);
    restoreIconSvg.appendChild(path2);
    restoreIcon.appendChild(restoreIconSvg);
    restoreIcon.style.marginRight = "6px";
    resetTemplateBtn.buttonEl.prepend(restoreIcon);
    resetTemplateBtn.onClick(async () => {
      await this.settingsManager.updateSettings({
        customTemplate: "",
        hasCustomTemplate: false
      });
      const defaultTemplate = this.settingsManager.getTemplateByLanguage();
      textarea.setValue(defaultTemplate);
      this.updatePreview(this.previewEl, defaultTemplate);
      resetTemplateBtn.buttonEl.style.backgroundColor = "var(--background-modifier-success)";
      setTimeout(() => {
        resetTemplateBtn.buttonEl.style.backgroundColor = "";
      }, 1e3);
    });
    previewHeader.appendChild(previewBtnContainer);
    previewHeader.appendChild(resetBtnContainer);
    templateContainer.appendChild(previewHeader);
    templateSetting.controlEl.appendChild(templateContainer);
    const resetContainer = document.createElement("div");
    resetContainer.style.display = "flex";
    resetContainer.style.justifyContent = "flex-end";
    resetContainer.style.marginTop = "20px";
    resetContainer.style.marginBottom = "10px";
    containerEl.appendChild(resetContainer);
    const resetDefaultBtn = new import_obsidian3.ButtonComponent(resetContainer).setButtonText(getTranslation("settings.resetToDefault"));
    resetDefaultBtn.buttonEl.classList.add(TextCenterCSS, "danger-button");
    const resetIcon = document.createElement("span");
    resetIcon.classList.add("svg-icon");
    const resetIconSvg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    resetIconSvg.setAttribute("viewBox", "0 0 24 24");
    resetIconSvg.setAttribute("fill", "none");
    resetIconSvg.setAttribute("stroke", "currentColor");
    resetIconSvg.setAttribute("stroke-width", "2");
    resetIconSvg.setAttribute("stroke-linecap", "round");
    resetIconSvg.setAttribute("stroke-linejoin", "round");
    const resetPath1 = document.createElementNS("http://www.w3.org/2000/svg", "path");
    resetPath1.setAttribute("d", "M3 2v6h6");
    const resetPath2 = document.createElementNS("http://www.w3.org/2000/svg", "path");
    resetPath2.setAttribute("d", "M21 12A9 9 0 0 0 6 5.3L3 8");
    const resetPath3 = document.createElementNS("http://www.w3.org/2000/svg", "path");
    resetPath3.setAttribute("d", "M21 22v-6h-6");
    const resetPath4 = document.createElementNS("http://www.w3.org/2000/svg", "path");
    resetPath4.setAttribute("d", "M3 12a9 9 0 0 0 15 6.7l3-2.7");
    resetIconSvg.appendChild(resetPath1);
    resetIconSvg.appendChild(resetPath2);
    resetIconSvg.appendChild(resetPath3);
    resetIconSvg.appendChild(resetPath4);
    resetIcon.appendChild(resetIconSvg);
    resetIcon.style.marginRight = "6px";
    resetDefaultBtn.buttonEl.prepend(resetIcon);
    resetDefaultBtn.onClick(async () => {
      await this.settingsManager.resetToDefaults();
      this.display();
    });
    const addTaskContainer = document.createElement("div");
    addTaskContainer.style.display = "flex";
    addTaskContainer.style.justifyContent = "flex-end";
    addTaskContainer.style.marginTop = "20px";
    containerEl.appendChild(addTaskContainer);
    this.addTaskButton = new import_obsidian3.ButtonComponent(addTaskContainer).setButtonText(getTranslation("settings.addTaskButton")).setCta();
    if (this.addTaskButton && this.addTaskButton.buttonEl) {
      this.addTaskButton.buttonEl.addClass(TextCenterCSS);
      this.addTaskButton.buttonEl.style.textAlign = "center";
      this.addTaskButton.buttonEl.style.display = "flex";
      this.addTaskButton.buttonEl.style.alignItems = "center";
      this.addTaskButton.buttonEl.style.justifyContent = "center";
    }
    this.addTaskButton.onClick(async () => {
      var _a;
      const rootDir = this.settingsManager.getSettings().rootDir;
      if (this.addTaskButton && this.addTaskButton.buttonEl) {
        this.addTaskButton.buttonEl.classList.add("loading");
      }
      (_a = this.addTaskButton) == null ? void 0 : _a.setDisabled(true);
      try {
        await this.taskGenerator.addTaskManually();
      } catch (e) {
        console.error("\u6DFB\u52A0\u4EFB\u52A1\u51FA\u9519:", e);
        new import_obsidian3.Notice(`\u6DFB\u52A0\u4EFB\u52A1\u5931\u8D25: ${e.message || e}`);
      } finally {
        setTimeout(() => {
          var _a2;
          if (this.addTaskButton && this.addTaskButton.buttonEl) {
            this.addTaskButton.buttonEl.classList.remove("loading");
          }
          (_a2 = this.addTaskButton) == null ? void 0 : _a2.setDisabled(false);
        }, 500);
      }
    });
    const addTaskIcon = document.createElement("span");
    addTaskIcon.classList.add("svg-icon");
    const addTaskIconSvg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    addTaskIconSvg.setAttribute("viewBox", "0 0 24 24");
    addTaskIconSvg.setAttribute("fill", "none");
    addTaskIconSvg.setAttribute("stroke", "currentColor");
    addTaskIconSvg.setAttribute("stroke-width", "2");
    addTaskIconSvg.setAttribute("stroke-linecap", "round");
    addTaskIconSvg.setAttribute("stroke-linejoin", "round");
    const addLine1 = document.createElementNS("http://www.w3.org/2000/svg", "line");
    addLine1.setAttribute("x1", "12");
    addLine1.setAttribute("y1", "5");
    addLine1.setAttribute("x2", "12");
    addLine1.setAttribute("y2", "19");
    const addLine2 = document.createElementNS("http://www.w3.org/2000/svg", "line");
    addLine2.setAttribute("x1", "5");
    addLine2.setAttribute("y1", "12");
    addLine2.setAttribute("x2", "19");
    addLine2.setAttribute("y2", "12");
    addTaskIconSvg.appendChild(addLine1);
    addTaskIconSvg.appendChild(addLine2);
    addTaskIcon.appendChild(addTaskIconSvg);
    addTaskIcon.style.marginRight = "6px";
    this.addTaskButton.buttonEl.prepend(addTaskIcon);
  }
  /**
   * 更新模板预览
   */
  updatePreview(previewEl, template) {
    if (!previewEl)
      return;
    const renderedContent = renderTemplate(template);
    previewEl.empty();
    const lines = renderedContent.split("\n");
    lines.forEach((line, index) => {
      if (line.trim()) {
        const lineEl = previewEl.createEl("div");
        lineEl.textContent = line;
        lineEl.style.textAlign = "left";
      } else if (index < lines.length - 1) {
        previewEl.createEl("br");
      }
    });
    previewEl.style.textAlign = "left";
  }
  /**
   * 切换预览的显示/隐藏
   */
  togglePreview(previewEl) {
    if (!previewEl)
      return;
    if (previewEl.style.display === "none") {
      previewEl.style.display = "block";
      previewEl.classList.add("visible");
    } else {
      previewEl.style.display = "none";
      previewEl.classList.remove("visible");
    }
  }
};
var SettingsManager = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.settings = Object.assign({}, DEFAULT_SETTINGS);
  }
  /**
   * 获取当前设置
   */
  getSettings() {
    return this.settings;
  }
  /**
   * 更新设置并保存
   * @param settings 要更新的设置
   */
  async updateSettings(settings) {
    this.settings = {
      ...this.settings,
      ...settings
    };
    await this.saveSettings();
    this.updateCurrentLanguage();
  }
  /**
   * 保存设置到数据存储
   */
  async saveSettings() {
    await this.plugin.saveData(this.settings);
  }
  /**
   * 加载设置
   */
  async loadSettings() {
    const loadedData = await this.plugin.loadData();
    if (loadedData) {
      this.settings = {
        ...DEFAULT_SETTINGS,
        ...loadedData
      };
      this.ensureSettingsCompleteness();
    } else {
      this.settings = {
        ...DEFAULT_SETTINGS,
        autoGenerateMode: "workday" /* WORKDAY */
      };
    }
    this.updateCurrentLanguage();
  }
  /**
   * 确保设置完整性，为新增的设置项提供默认值
   */
  ensureSettingsCompleteness() {
    const defaultKeys = Object.keys(DEFAULT_SETTINGS);
    defaultKeys.forEach((key) => {
      if (!(key in this.settings)) {
        this.settings[key] = DEFAULT_SETTINGS[key];
      }
    });
  }
  /**
   * 恢复默认设置
   */
  async resetToDefaults() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS);
    await this.saveSettings();
    this.updateCurrentLanguage();
  }
  /**
   * 根据语言获取当前使用的模板
   * 如果当前模板不是默认模板，则不再区分语言
   */
  getCurrentTemplate() {
    const language = this.getCurrentLanguage();
    if (language === "zh") {
      if (this.settings.templateZh !== DEFAULT_TEMPLATE_ZH) {
        return this.settings.templateZh;
      }
      if (this.settings.templateEn !== DEFAULT_TEMPLATE_EN) {
        return this.settings.templateEn;
      }
      return this.settings.templateZh;
    } else {
      if (this.settings.templateEn !== DEFAULT_TEMPLATE_EN) {
        return this.settings.templateEn;
      }
      if (this.settings.templateZh !== DEFAULT_TEMPLATE_ZH) {
        return this.settings.templateZh;
      }
      return this.settings.templateEn;
    }
  }
  /**
   * 获取当前语言设置
   */
  getCurrentLanguage() {
    if (this.settings.language === "auto" /* AUTO */) {
      const systemLanguage = window.navigator.language.toLowerCase();
      return systemLanguage.startsWith("zh") ? "zh" : "en";
    }
    return this.settings.language;
  }
  /**
   * 更新当前语言
   */
  updateCurrentLanguage() {
    const language = this.getCurrentLanguage();
    setCurrentLanguage(language);
  }
  /**
   * 获取当前语言的模板
   */
  getTemplateByLanguage() {
    const language = this.getCurrentLanguage();
    if (language === "zh") {
      if (this.settings.templateZh !== DEFAULT_TEMPLATE_ZH) {
        return this.settings.templateZh;
      }
      if (this.settings.templateEn !== DEFAULT_TEMPLATE_EN) {
        return this.settings.templateEn;
      }
      return this.settings.templateZh;
    } else {
      if (this.settings.templateEn !== DEFAULT_TEMPLATE_EN) {
        return this.settings.templateEn;
      }
      if (this.settings.templateZh !== DEFAULT_TEMPLATE_ZH) {
        return this.settings.templateZh;
      }
      return this.settings.templateEn;
    }
  }
  /**
   * 检查是否存在自定义模板
   */
  hasCustomTemplate() {
    return !!this.settings.customTemplate;
  }
};

// src/ui/icons.ts
var DAILY_TASK_ICON = `<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
    <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/>
</svg>`;

// src/main.ts
var DailyTaskPlugin = class extends import_obsidian4.Plugin {
  /**
   * 插件加载时调用
   */
  async onload() {
    (0, import_obsidian4.addIcon)("daily-task", DAILY_TASK_ICON);
    this.settingsManager = new SettingsManager(this);
    await this.settingsManager.loadSettings();
    this.taskGenerator = new TaskGenerator(this.app, this.settingsManager);
    setCurrentLanguage(this.settingsManager.getCurrentLanguage());
    this.addSettingTab(new DailyTaskSettingTab(this.app, this));
    this.addCommand({
      id: "add-daily-task",
      name: "\u624B\u52A8\u6DFB\u52A0\u4ECA\u65E5\u4EFB\u52A1",
      callback: async () => {
        await this.taskGenerator.addTaskManually();
      }
    });
    setTimeout(async () => {
      await this.checkAutoGenerate();
    }, 1e4);
  }
  /**
   * 插件卸载时调用
   */
  onunload() {
  }
  /**
   * 检查是否需要自动生成任务
   */
  async checkAutoGenerate() {
    const settings = this.settingsManager.getSettings();
    switch (settings.autoGenerateMode) {
      case "daily" /* DAILY */:
        await this.taskGenerator.generateDailyTask(false, true);
        break;
      case "workday" /* WORKDAY */:
        if (isWorkday()) {
          await this.taskGenerator.generateDailyTask(false, true);
        }
        break;
      case "none" /* NONE */:
      default:
        break;
    }
  }
};

/* nosourcemap */