/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => StarNotebookLMPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var NOTEBOOKLM_VIEW_TYPE = "notebooklm-webview";
var DEFAULT_SETTINGS = {
  language: "auto",
  includeMetadata: true,
  includeFrontmatter: false,
  sourceAddMethod: "api"
  // 기본값: API 방식
};
function detectLanguage() {
  var _a, _b;
  const locale = ((_b = (_a = window.moment) == null ? void 0 : _a.locale) == null ? void 0 : _b.call(_a)) || navigator.language || "en";
  return locale.startsWith("ko") ? "ko" : "en";
}
function getLanguage(setting) {
  if (setting === "auto")
    return detectLanguage();
  return setting;
}
var i18n = {
  ko: {
    // ribbons & commands
    "ribbon.send": "NotebookLM\uC5D0 \uC804\uC1A1",
    "ribbon.open": "NotebookLM \uC5F4\uAE30",
    "cmd.sendNote": "\uD604\uC7AC \uB178\uD2B8\uB97C NotebookLM\uC5D0 \uC804\uC1A1",
    "cmd.sendSelection": "\uC120\uD0DD\uB41C \uD14D\uC2A4\uD2B8\uB97C NotebookLM\uC5D0 \uC804\uC1A1",
    "cmd.open": "NotebookLM \uC5F4\uAE30",
    // context menus
    "menu.send": "NotebookLM\uC5D0 \uC804\uC1A1",
    "menu.sendMulti": "NotebookLM\uC5D0 \uC804\uC1A1 ({count}\uAC1C)",
    "menu.sendSelection": "\uC120\uD0DD \uC601\uC5ED\uC744 NotebookLM\uC5D0 \uC804\uC1A1",
    // status bar
    "status.queue": "\u{1F4CB} Star: {count}",
    "status.queueTooltip": "Star NotebookLM\n\uB300\uAE30\uC5F4: {count}\uAC1C",
    "status.ready": "\u{1F4D8} Star NLM",
    "status.readyTooltip": "Star NotebookLM \uC900\uBE44\uB428",
    // notices
    "notice.selectText": "\uD14D\uC2A4\uD2B8\uB97C \uC120\uD0DD\uD574\uC8FC\uC138\uC694",
    "notice.noActiveNote": "\uD65C\uC131 \uB178\uD2B8\uAC00 \uC5C6\uC2B5\uB2C8\uB2E4",
    "notice.fetchingNotebooks": "\uB178\uD2B8\uBD81 \uBAA9\uB85D\uC744 \uAC00\uC838\uC624\uB294 \uC911...",
    "notice.movingToNotebook": '"{title}" \uB178\uD2B8\uBD81\uC73C\uB85C \uC774\uB3D9 \uC911...',
    "notice.createNewManual": "NotebookLM\uC5D0\uC11C \uC0C8 \uB178\uD2B8\uBD81\uC744 \uB9CC\uB4E4\uC5B4\uC8FC\uC138\uC694.\n\uB178\uD2B8\uAC00 \uB300\uAE30\uC5F4\uC5D0 \uCD94\uAC00\uB418\uC5C8\uC2B5\uB2C8\uB2E4.",
    "notice.preparingNotes": "{count}\uAC1C \uB178\uD2B8 \uC900\uBE44 \uC911...",
    "notice.sendingNotes": '"{title}" \uB178\uD2B8\uBD81\uC73C\uB85C {count}\uAC1C \uB178\uD2B8 \uC804\uC1A1 \uC911...',
    "notice.creatingNotebook": "\uC0C8 \uB178\uD2B8\uBD81 \uC0DD\uC131 \uC911...",
    "notice.creatingNotebookAPI": "\uC0C8 \uB178\uD2B8\uBD81 \uC0DD\uC131 \uC911 (API)...",
    "notice.notebookCreated": '\u2705 \uB178\uD2B8\uBD81 "{title}" \uC0DD\uC131 \uC644\uB8CC!',
    "notice.waitingNotebook": "\uC0C8 \uB178\uD2B8\uBD81\uC774 \uC0DD\uC131\uB418\uBA74 \uC18C\uC2A4\uAC00 \uC790\uB3D9 \uCD94\uAC00\uB429\uB2C8\uB2E4.\n\uC7A0\uC2DC \uAE30\uB2E4\uB824\uC8FC\uC138\uC694...",
    "notice.notebookCreateFailed": "\uC0C8 \uB178\uD2B8\uBD81 \uC0DD\uC131\uC5D0 \uC2E4\uD328\uD588\uC2B5\uB2C8\uB2E4. \uC218\uB3D9\uC73C\uB85C \uC0DD\uC131\uD574\uC8FC\uC138\uC694.",
    "notice.addingTextSource": '"{title}" \uD14D\uC2A4\uD2B8 \uC18C\uC2A4 API\uB85C \uCD94\uAC00 \uC911...',
    "notice.selectNotebookFirst": "\uB178\uD2B8\uBD81\uC744 \uBA3C\uC800 \uC120\uD0DD\uD574\uC8FC\uC138\uC694.",
    "notice.noAuthToken": "\uC778\uC99D \uD1A0\uD070\uC744 \uCC3E\uC744 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4. DOM \uBC29\uC2DD\uC73C\uB85C \uC804\uD658...",
    "notice.textSourceAdded": '\u2705 "{title}" \uD14D\uC2A4\uD2B8 \uC18C\uC2A4 \uCD94\uAC00 \uC644\uB8CC!',
    "notice.apiFailed": "API \uC2E4\uD328. DOM \uBC29\uC2DD\uC73C\uB85C \uC7AC\uC2DC\uB3C4...",
    "notice.addingUrlSource": '"{title}" URL \uC18C\uC2A4 API\uB85C \uCD94\uAC00 \uC911...',
    "notice.urlSourceAdded": '\u2705 "{title}" URL \uC18C\uC2A4 \uCD94\uAC00 \uC644\uB8CC!',
    "notice.addingDomSource": '"{title}" DOM \uBC29\uC2DD\uC73C\uB85C \uC18C\uC2A4 \uCD94\uAC00 \uC911...',
    "notice.sourceAdded": '\u2705 "{title}" \uC18C\uC2A4\uAC00 \uCD94\uAC00\uB418\uC5C8\uC2B5\uB2C8\uB2E4!',
    "notice.manualInsert": '\u{1F4DD} \uD14D\uC2A4\uD2B8 \uC785\uB825 \uC644\uB8CC!\n"\uC0BD\uC785" \uBC84\uD2BC\uC744 \uD074\uB9AD\uD574\uC8FC\uC138\uC694.',
    "notice.clipboardFallback": "\u{1F4CB} \uC790\uB3D9 \uC785\uB825 \uC2E4\uD328. \uD074\uB9BD\uBCF4\uB4DC\uC5D0 \uBCF5\uC0AC\uB428.\n\nCmd+V\uB85C \uBD99\uC5EC\uB123\uAE30 \uD6C4 \uC0BD\uC785 \uD074\uB9AD",
    "notice.clipboardCopied": '\u{1F4CB} "{title}" \uD074\uB9BD\uBCF4\uB4DC\uC5D0 \uBCF5\uC0AC\uB428.\n\n\uC218\uB3D9\uC73C\uB85C \uBD99\uC5EC\uB123\uAE30 \uD574\uC8FC\uC138\uC694.',
    "notice.sourceAddFailed": "\uC18C\uC2A4 \uCD94\uAC00\uC5D0 \uC2E4\uD328\uD588\uC2B5\uB2C8\uB2E4.",
    "notice.linkSourceAdded": '\u2705 "{title}" \uB9C1\uD06C \uC18C\uC2A4\uAC00 \uCD94\uAC00\uB418\uC5C8\uC2B5\uB2C8\uB2E4!\n({link})',
    "notice.manualUrlInsert": '\u{1F4DD} URL \uC785\uB825 \uC644\uB8CC!\n"\uC0BD\uC785" \uBC84\uD2BC\uC744 \uD074\uB9AD\uD574\uC8FC\uC138\uC694.',
    "notice.urlClipboardFallback": "\u{1F4CB} \uC790\uB3D9 \uC785\uB825 \uC2E4\uD328. URL\uC774 \uD074\uB9BD\uBCF4\uB4DC\uC5D0 \uBCF5\uC0AC\uB428.\n\n{link}",
    "notice.urlClipboardCopied": '\u{1F4CB} "{title}" URL\uC774 \uD074\uB9BD\uBCF4\uB4DC\uC5D0 \uBCF5\uC0AC\uB428.\n\n\uC218\uB3D9\uC73C\uB85C \uBD99\uC5EC\uB123\uAE30 \uD574\uC8FC\uC138\uC694.',
    "notice.linkAddFailed": "\uB9C1\uD06C \uC18C\uC2A4 \uCD94\uAC00\uC5D0 \uC2E4\uD328\uD588\uC2B5\uB2C8\uB2E4.",
    "notice.webviewNotOpen": "NotebookLM \uC6F9\uBDF0\uAC00 \uC5F4\uB824\uC788\uC9C0 \uC54A\uC2B5\uB2C8\uB2E4.\n\uBA3C\uC800 NotebookLM\uC744 \uC5F4\uC5B4\uC8FC\uC138\uC694.",
    "notice.collectingDom": "DOM \uC815\uBCF4 \uC218\uC9D1 \uC911...",
    "notice.domSaved": "DOM \uC815\uBCF4\uAC00 {path}\uC5D0 \uC800\uC7A5\uB418\uC5C8\uC2B5\uB2C8\uB2E4.\n\n\uBC84\uD2BC {buttons}\uAC1C\n\uB178\uD2B8\uBD81 \uB9C1\uD06C {links}\uAC1C\n\uC785\uB825\uD544\uB4DC {inputs}\uAC1C\n\uB2E4\uC774\uC5BC\uB85C\uADF8 {dialogs}\uAC1C",
    "notice.domFailed": "DOM \uC815\uBCF4 \uC218\uC9D1 \uC2E4\uD328: {error}",
    "notice.emptyQueue": "\uB300\uAE30\uC5F4\uC774 \uBE44\uC5B4\uC788\uC2B5\uB2C8\uB2E4",
    "notice.selectNotebook": "\uBA3C\uC800 \uB178\uD2B8\uBD81\uC744 \uC120\uD0DD\uD574\uC8FC\uC138\uC694",
    "notice.addingFromQueue": '"{title}" \uCD94\uAC00 \uC911...',
    "notice.addedFromQueue": '"{title}" \uCD94\uAC00 \uC644\uB8CC!',
    "notice.batchProgress": "\uCD94\uAC00 \uC911... ({current}/{total}) - {title}",
    "notice.batchAllSuccess": "\u2705 {count}\uAC1C \uB178\uD2B8 \uBAA8\uB450 \uCD94\uAC00 \uC644\uB8CC!",
    "notice.batchPartial": "\uC644\uB8CC! \uC131\uACF5: {success}\uAC1C, \uC2E4\uD328: {failed}\uAC1C",
    "notice.refreshFailed": "\uB178\uD2B8\uBD81 \uBAA9\uB85D \uAC00\uC838\uC624\uAE30 \uC2E4\uD328. NotebookLM \uC6F9\uBDF0\uAC00 \uB85C\uB4DC\uB418\uC5C8\uB294\uC9C0 \uD655\uC778\uD574\uC8FC\uC138\uC694.",
    // modal
    "modal.selectNotebook": "\uB178\uD2B8\uBD81 \uC120\uD0DD",
    "modal.loading": "\uB85C\uB529 \uC911...",
    "modal.refresh": "\uC0C8\uB85C\uACE0\uCE68",
    "modal.whereToAdd": '"{title}" \uB178\uD2B8\uB97C \uC5B4\uB514\uC5D0 \uCD94\uAC00\uD560\uAE4C\uC694?',
    "modal.newNotebook": "\uC0C8 \uB178\uD2B8\uBD81",
    "modal.createNew": "\uC0C8 \uB178\uD2B8\uBD81 \uB9CC\uB4E4\uAE30",
    "modal.createNewDesc": "NotebookLM\uC5D0\uC11C \uC0C8 \uB178\uD2B8\uBD81\uC744 \uC0DD\uC131\uD569\uB2C8\uB2E4",
    "modal.existingNotebooks": "\uAE30\uC874 \uB178\uD2B8\uBD81 ({count}\uAC1C)",
    "modal.noNotebooks": "\uAE30\uC874 \uB178\uD2B8\uBD81\uC744 \uCC3E\uC744 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4.",
    "modal.noNotebooksHint": "NotebookLM \uC6F9\uBDF0\uAC00 \uC644\uC804\uD788 \uB85C\uB4DC\uB41C \uD6C4 \uC704\uC758 <strong>\uC0C8\uB85C\uACE0\uCE68</strong> \uBC84\uD2BC\uC744 \uB20C\uB7EC\uC8FC\uC138\uC694.",
    "modal.cancel": "\uCDE8\uC18C",
    // settings
    "settings.title": "Star NotebookLM \uC124\uC815",
    "settings.language": "\uC5B8\uC5B4",
    "settings.languageDesc": "\uD50C\uB7EC\uADF8\uC778 UI \uC5B8\uC5B4",
    "settings.langAuto": "\uC790\uB3D9 \uAC10\uC9C0",
    "settings.langKo": "\uD55C\uAD6D\uC5B4",
    "settings.langEn": "English",
    "settings.includeMetadata": "\uBA54\uD0C0\uB370\uC774\uD130 \uD3EC\uD568",
    "settings.includeMetadataDesc": "\uB178\uD2B8 \uC804\uC1A1 \uC2DC \uC0DD\uC131/\uC218\uC815 \uC2DC\uAC04, \uD0DC\uADF8 \uB4F1 \uBA54\uD0C0\uB370\uC774\uD130 \uD3EC\uD568",
    "settings.includeFrontmatter": "Frontmatter \uD3EC\uD568",
    "settings.includeFrontmatterDesc": "\uB178\uD2B8 \uC804\uC1A1 \uC2DC YAML frontmatter \uD3EC\uD568",
    "settings.sourceMethod": "\uC18C\uC2A4 \uCD94\uAC00 \uBC29\uC2DD",
    "settings.sourceMethodDesc": "NotebookLM\uC5D0 \uC18C\uC2A4\uB97C \uCD94\uAC00\uD558\uB294 \uBC29\uC2DD\uC744 \uC120\uD0DD\uD569\uB2C8\uB2E4",
    "settings.sourceApi": "API \uC9C1\uC811 \uD638\uCD9C (\uBE60\uB984, \uAD8C\uC7A5)",
    "settings.sourceDom": "DOM \uC870\uC791 (\uC548\uC815\uC801)",
    "settings.usage": "\uC0AC\uC6A9\uBC95",
    "settings.usage1": "1. \uC67C\uCABD \uB9AC\uBCF8\uC758 \uCC45 \uC544\uC774\uCF58(book-open)\uC744 \uD074\uB9AD\uD558\uC5EC NotebookLM \uD328\uB110\uC744 \uC5FD\uB2C8\uB2E4.",
    "settings.usage2": "2. NotebookLM \uD328\uB110\uC5D0\uC11C Google \uACC4\uC815\uC73C\uB85C \uB85C\uADF8\uC778\uD569\uB2C8\uB2E4.",
    "settings.usage3": "3. \uB178\uD2B8\uB97C \uC804\uC1A1\uD558\uB294 \uBC29\uBC95:",
    "settings.usageMethod1": "\uB9AC\uBCF8\uC758 \uC804\uC1A1 \uC544\uC774\uCF58(send) \uD074\uB9AD",
    "settings.usageMethod2": '\uD30C\uC77C \uD0D0\uC0C9\uAE30\uC5D0\uC11C \uB178\uD2B8 \uC6B0\uD074\uB9AD \u2192 "NotebookLM\uC5D0 \uC804\uC1A1"',
    "settings.usageMethod3": '\uC5D0\uB514\uD130\uC5D0\uC11C \uC6B0\uD074\uB9AD \u2192 "NotebookLM\uC5D0 \uC804\uC1A1" (\uC804\uCCB4 \uB178\uD2B8)',
    "settings.usageMethod4": '\uD14D\uC2A4\uD2B8 \uC120\uD0DD \uD6C4 \uC6B0\uD074\uB9AD \u2192 "\uC120\uD0DD \uC601\uC5ED\uC744 NotebookLM\uC5D0 \uC804\uC1A1"',
    "settings.usage4": "4. \uB178\uD2B8\uBD81 \uC120\uD0DD \uBAA8\uB2EC\uC5D0\uC11C \uAE30\uC874 \uB178\uD2B8\uBD81\uC744 \uC120\uD0DD\uD558\uAC70\uB098 \uC0C8\uB85C \uB9CC\uB4ED\uB2C8\uB2E4.",
    // view
    "view.displayText": "NotebookLM",
    "view.refresh": "\u{1F504} \uC0C8\uB85C\uACE0\uCE68",
    "view.notebookList": "\u{1F4DA} \uB178\uD2B8\uBD81 \uBAA9\uB85D"
  },
  en: {
    "ribbon.send": "Send to NotebookLM",
    "ribbon.open": "Open NotebookLM",
    "cmd.sendNote": "Send current note to NotebookLM",
    "cmd.sendSelection": "Send selected text to NotebookLM",
    "cmd.open": "Open NotebookLM",
    "menu.send": "Send to NotebookLM",
    "menu.sendMulti": "Send to NotebookLM ({count})",
    "menu.sendSelection": "Send selection to NotebookLM",
    "status.queue": "\u{1F4CB} Star: {count}",
    "status.queueTooltip": "Star NotebookLM\nQueue: {count}",
    "status.ready": "\u{1F4D8} Star NLM",
    "status.readyTooltip": "Star NotebookLM Ready",
    "notice.selectText": "Please select some text",
    "notice.noActiveNote": "No active note",
    "notice.fetchingNotebooks": "Fetching notebook list...",
    "notice.movingToNotebook": 'Moving to "{title}" notebook...',
    "notice.createNewManual": "Please create a new notebook in NotebookLM.\nNote has been added to the queue.",
    "notice.preparingNotes": "Preparing {count} notes...",
    "notice.sendingNotes": 'Sending {count} notes to "{title}" notebook...',
    "notice.creatingNotebook": "Creating new notebook...",
    "notice.creatingNotebookAPI": "Creating new notebook (API)...",
    "notice.notebookCreated": '\u2705 Notebook "{title}" created!',
    "notice.waitingNotebook": "Source will be added automatically when notebook is ready.\nPlease wait...",
    "notice.notebookCreateFailed": "Failed to create notebook. Please create one manually.",
    "notice.addingTextSource": 'Adding "{title}" as text source via API...',
    "notice.selectNotebookFirst": "Please select a notebook first.",
    "notice.noAuthToken": "Auth token not found. Switching to DOM method...",
    "notice.textSourceAdded": '\u2705 "{title}" text source added!',
    "notice.apiFailed": "API failed. Retrying with DOM method...",
    "notice.addingUrlSource": 'Adding "{title}" as URL source via API...',
    "notice.urlSourceAdded": '\u2705 "{title}" URL source added!',
    "notice.addingDomSource": 'Adding "{title}" via DOM method...',
    "notice.sourceAdded": '\u2705 "{title}" source added!',
    "notice.manualInsert": '\u{1F4DD} Text input complete!\nPlease click the "Insert" button.',
    "notice.clipboardFallback": "\u{1F4CB} Auto-input failed. Copied to clipboard.\n\nUse Cmd+V to paste, then click Insert",
    "notice.clipboardCopied": '\u{1F4CB} "{title}" copied to clipboard.\n\nPlease paste manually.',
    "notice.sourceAddFailed": "Failed to add source.",
    "notice.linkSourceAdded": '\u2705 "{title}" link source added!\n({link})',
    "notice.manualUrlInsert": '\u{1F4DD} URL input complete!\nPlease click the "Insert" button.',
    "notice.urlClipboardFallback": "\u{1F4CB} Auto-input failed. URL copied to clipboard.\n\n{link}",
    "notice.urlClipboardCopied": '\u{1F4CB} "{title}" URL copied to clipboard.\n\nPlease paste manually.',
    "notice.linkAddFailed": "Failed to add link source.",
    "notice.webviewNotOpen": "NotebookLM webview is not open.\nPlease open NotebookLM first.",
    "notice.collectingDom": "Collecting DOM info...",
    "notice.domSaved": "DOM info saved to {path}.\n\nButtons: {buttons}\nNotebook links: {links}\nInputs: {inputs}\nDialogs: {dialogs}",
    "notice.domFailed": "DOM collection failed: {error}",
    "notice.emptyQueue": "Queue is empty",
    "notice.selectNotebook": "Please select a notebook first",
    "notice.addingFromQueue": 'Adding "{title}"...',
    "notice.addedFromQueue": '"{title}" added!',
    "notice.batchProgress": "Adding... ({current}/{total}) - {title}",
    "notice.batchAllSuccess": "\u2705 All {count} notes added!",
    "notice.batchPartial": "Done! Success: {success}, Failed: {failed}",
    "notice.refreshFailed": "Failed to fetch notebooks. Make sure NotebookLM webview is loaded.",
    "modal.selectNotebook": "Select Notebook",
    "modal.loading": "Loading...",
    "modal.refresh": "Refresh",
    "modal.whereToAdd": 'Where to add "{title}"?',
    "modal.newNotebook": "New Notebook",
    "modal.createNew": "Create New Notebook",
    "modal.createNewDesc": "Create a new notebook in NotebookLM",
    "modal.existingNotebooks": "Existing Notebooks ({count})",
    "modal.noNotebooks": "No existing notebooks found.",
    "modal.noNotebooksHint": "Please wait for NotebookLM webview to fully load, then click <strong>Refresh</strong> above.",
    "modal.cancel": "Cancel",
    "settings.title": "Star NotebookLM Settings",
    "settings.language": "Language",
    "settings.languageDesc": "Plugin UI language",
    "settings.langAuto": "Auto Detect",
    "settings.langKo": "\uD55C\uAD6D\uC5B4",
    "settings.langEn": "English",
    "settings.includeMetadata": "Include Metadata",
    "settings.includeMetadataDesc": "Include creation/modification time, tags when sending notes",
    "settings.includeFrontmatter": "Include Frontmatter",
    "settings.includeFrontmatterDesc": "Include YAML frontmatter when sending notes",
    "settings.sourceMethod": "Source Add Method",
    "settings.sourceMethodDesc": "Method to add sources to NotebookLM",
    "settings.sourceApi": "API Direct Call (fast, recommended)",
    "settings.sourceDom": "DOM Manipulation (stable)",
    "settings.usage": "Usage",
    "settings.usage1": "1. Click the book icon (book-open) in the left ribbon to open NotebookLM panel.",
    "settings.usage2": "2. Log in with your Google account in the NotebookLM panel.",
    "settings.usage3": "3. Ways to send notes:",
    "settings.usageMethod1": "Click the send icon in the ribbon",
    "settings.usageMethod2": 'Right-click a note in file explorer \u2192 "Send to NotebookLM"',
    "settings.usageMethod3": 'Right-click in editor \u2192 "Send to NotebookLM" (full note)',
    "settings.usageMethod4": 'Select text, right-click \u2192 "Send selection to NotebookLM"',
    "settings.usage4": "4. In the notebook selection modal, choose an existing notebook or create new.",
    "view.displayText": "NotebookLM",
    "view.refresh": "\u{1F504} Refresh",
    "view.notebookList": "\u{1F4DA} Notebooks"
  }
};
var currentLang = "ko";
function t(key, params) {
  var _a, _b;
  let text = ((_a = i18n[currentLang]) == null ? void 0 : _a[key]) || ((_b = i18n["en"]) == null ? void 0 : _b[key]) || key;
  if (params) {
    for (const [k, v] of Object.entries(params)) {
      text = text.replace(new RegExp(`\\{${k}\\}`, "g"), String(v));
    }
  }
  return text;
}
var StarNotebookLMPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.noteQueue = /* @__PURE__ */ new Map();
    this.currentPageState = null;
  }
  async onload() {
    await this.loadSettings();
    currentLang = getLanguage(this.settings.language);
    this.registerView(
      NOTEBOOKLM_VIEW_TYPE,
      (leaf) => new NotebookLMView(leaf, this)
    );
    this.statusBarItem = this.addStatusBarItem();
    this.updateStatusBar();
    this.addRibbonIcon("send", t("ribbon.send"), async () => {
      await this.sendCurrentNoteToQueue();
    });
    this.addRibbonIcon("book-open", t("ribbon.open"), async () => {
      await this.openNotebookLMView();
    });
    this.addCommand({
      id: "send-to-notebooklm",
      name: t("cmd.sendNote"),
      editorCallback: async (editor, view) => {
        await this.sendCurrentNoteToQueue();
      }
    });
    this.addCommand({
      id: "send-selection-to-notebooklm",
      name: t("cmd.sendSelection"),
      editorCallback: async (editor, view) => {
        var _a;
        const selection = editor.getSelection();
        if (selection) {
          await this.sendTextToQueue(selection, ((_a = view.file) == null ? void 0 : _a.basename) || "Selection");
        } else {
          new import_obsidian.Notice(t("notice.selectText"));
        }
      }
    });
    this.addCommand({
      id: "open-notebooklm",
      name: t("cmd.open"),
      callback: async () => {
        await this.openNotebookLMView();
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian.TFile && file.extension === "md") {
          menu.addItem((item) => {
            item.setTitle(t("menu.send")).setIcon("send").onClick(async () => {
              await this.sendFileToQueue(file);
            });
          });
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("files-menu", (menu, files, source) => {
        const mdFiles = files.filter((f) => f instanceof import_obsidian.TFile && f.extension === "md");
        if (mdFiles.length > 1) {
          menu.addItem((item) => {
            item.setTitle(t("menu.sendMulti", { count: mdFiles.length })).setIcon("send").onClick(async () => {
              await this.sendFilesToQueue(mdFiles);
            });
          });
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor, view) => {
        menu.addItem((item) => {
          item.setTitle(t("menu.send")).setIcon("send").onClick(async () => {
            await this.sendCurrentNoteToQueue();
          });
        });
        const selection = editor.getSelection();
        if (selection) {
          menu.addItem((item) => {
            item.setTitle(t("menu.sendSelection")).setIcon("text-select").onClick(async () => {
              var _a;
              await this.sendTextToQueue(selection, ((_a = view.file) == null ? void 0 : _a.basename) || "Selection");
            });
          });
        }
      })
    );
    this.addSettingTab(new StarNotebookLMSettingTab(this.app, this));
  }
  async onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  updateStatusBar() {
    const queueSize = this.noteQueue.size;
    if (queueSize > 0) {
      this.statusBarItem.setText(t("status.queue", { count: queueSize }));
      this.statusBarItem.setAttribute("title", t("status.queueTooltip", { count: queueSize }));
    } else {
      this.statusBarItem.setText(t("status.ready"));
      this.statusBarItem.setAttribute("title", t("status.readyTooltip"));
    }
  }
  // NotebookLM 웹뷰 열기
  async openNotebookLMView() {
    const existing = this.app.workspace.getLeavesOfType(NOTEBOOKLM_VIEW_TYPE);
    if (existing.length > 0) {
      this.app.workspace.revealLeaf(existing[0]);
    } else {
      const leaf = this.app.workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({
          type: NOTEBOOKLM_VIEW_TYPE,
          active: true
        });
        this.app.workspace.revealLeaf(leaf);
      }
    }
  }
  // NotebookLM 웹뷰 가져오기
  getNotebookLMView() {
    const leaves = this.app.workspace.getLeavesOfType(NOTEBOOKLM_VIEW_TYPE);
    if (leaves.length > 0) {
      return leaves[0].view;
    }
    return null;
  }
  async getCurrentNote() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!activeView || !activeView.file) {
      return null;
    }
    return await this.getFileContent(activeView.file);
  }
  async getFileContent(file) {
    var _a, _b;
    let content = await this.app.vault.read(file);
    const cache = this.app.metadataCache.getFileCache(file);
    let shareLink;
    if ((_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.share_link) {
      shareLink = cache.frontmatter.share_link;
    }
    if (!this.settings.includeFrontmatter) {
      content = content.replace(/^---\n[\s\S]*?\n---\n/, "");
    }
    const note = {
      title: file.basename,
      content: content.trim(),
      path: file.path,
      shareLink
    };
    if (this.settings.includeMetadata) {
      note.metadata = {
        created: file.stat.ctime,
        modified: file.stat.mtime,
        tags: ((_b = cache == null ? void 0 : cache.tags) == null ? void 0 : _b.map((t2) => t2.tag)) || []
      };
    }
    return note;
  }
  async sendCurrentNoteToQueue() {
    const note = await this.getCurrentNote();
    if (!note) {
      new import_obsidian.Notice(t("notice.noActiveNote"));
      return;
    }
    await this.openNotebookLMView();
    const view = this.getNotebookLMView();
    if (view && view.webview) {
      new import_obsidian.Notice(t("notice.fetchingNotebooks"));
      view.webview.loadURL("https://notebooklm.google.com");
      setTimeout(async () => {
        const notebooks = await this.getNotebooksFromWebview();
        this.showNotebookModal(note, notebooks);
      }, 3e3);
    } else {
      this.showNotebookModal(note, []);
    }
  }
  // 노트북 선택 모달 표시
  async showNotebookSelectModal(note) {
    let notebooks = [];
    const view = this.getNotebookLMView();
    if (view && view.webview) {
      try {
        const result = await view.webview.executeJavaScript(`
					(function() {
						const notebooks = [];
						document.querySelectorAll('a[href*="/notebook/"]').forEach(el => {
							const href = el.getAttribute('href');
							const match = href.match(/\\/notebook\\/([^/]+)/);
							if (match) {
								let title = el.textContent.trim();
								if (!title || title.length > 100) {
									const titleEl = el.querySelector('[class*="title"], h2, h3, span');
									if (titleEl) title = titleEl.textContent.trim();
								}
								if (title && !notebooks.find(n => n.id === match[1])) {
									notebooks.push({
										id: match[1],
										title: title || 'Untitled',
										url: 'https://notebooklm.google.com' + href
									});
								}
							}
						});
						return notebooks;
					})();
				`);
        notebooks = result || [];
      } catch (error) {
        console.error("[Star NotebookLM] \uB178\uD2B8\uBD81 \uBAA9\uB85D \uAC00\uC838\uC624\uAE30 \uC2E4\uD328:", error);
      }
    }
    const modal = new NotebookSelectModal(this.app, this, notebooks, note.title, async (selectedNotebook) => {
      await this.openNotebookLMView();
      const nlmView = this.getNotebookLMView();
      if (selectedNotebook) {
        new import_obsidian.Notice(t("notice.movingToNotebook", { title: selectedNotebook.title }));
        if (nlmView && nlmView.webview) {
          nlmView.webview.loadURL(selectedNotebook.url);
          this.addToQueue(note);
          setTimeout(() => {
            nlmView.addFromQueue();
          }, 3e3);
        } else {
          this.addToQueue(note);
        }
      } else {
        new import_obsidian.Notice(t("notice.createNewManual"));
        this.addToQueue(note);
        if (nlmView && nlmView.webview) {
          nlmView.webview.loadURL("https://notebooklm.google.com");
        }
      }
    });
    modal.open();
  }
  async sendFileToQueue(file) {
    const note = await this.getFileContent(file);
    await this.openNotebookLMView();
    const view = this.getNotebookLMView();
    if (view && view.webview) {
      new import_obsidian.Notice(t("notice.fetchingNotebooks"));
      view.webview.loadURL("https://notebooklm.google.com");
      setTimeout(async () => {
        const notebooks = await this.getNotebooksFromWebview();
        this.showNotebookModal(note, notebooks);
      }, 3e3);
    } else {
      this.showNotebookModal(note, []);
    }
  }
  // 다중 파일 대기열에 추가 (배치 전송)
  async sendFilesToQueue(files) {
    const notes = await Promise.all(
      files.map((file) => this.getFileContent(file))
    );
    await this.openNotebookLMView();
    const view = this.getNotebookLMView();
    if (view && view.webview) {
      new import_obsidian.Notice(t("notice.preparingNotes", { count: notes.length }));
      view.webview.loadURL("https://notebooklm.google.com");
      setTimeout(async () => {
        const notebooks = await this.getNotebooksFromWebview();
        this.showBatchNotebookModal(notes, notebooks);
      }, 3e3);
    } else {
      this.showBatchNotebookModal(notes, []);
    }
  }
  // 배치용 노트북 선택 모달 표시
  showBatchNotebookModal(notes, notebooks) {
    const modal = new NotebookSelectModal(
      this.app,
      this,
      notebooks,
      t("notice.preparingNotes", { count: notes.length }),
      // 제목에 개수 표시
      async (selected) => {
        const view = this.getNotebookLMView();
        if (selected) {
          new import_obsidian.Notice(t("notice.sendingNotes", { title: selected.title, count: notes.length }));
          if (view && view.webview) {
            if (selected.url) {
              view.webview.loadURL(selected.url);
            } else {
              await view.webview.executeJavaScript(`
								(function() {
									const title = ${JSON.stringify(selected.title)};
									const viewType = ${JSON.stringify(selected.viewType || "table")};

									// \uBC29\uBC95 1: \uD14C\uC774\uBE14 \uD589 \uD074\uB9AD (\uBAA8\uBC14\uC77C \uBDF0)
									if (viewType === 'table') {
										const titleEls = document.querySelectorAll('.project-table-title');
										for (const el of titleEls) {
											if (el.textContent.trim() === title) {
												const row = el.closest('tr');
												if (row) {
													row.click();
													return { success: true, method: 'table' };
												}
											}
										}
									}

									// \uBC29\uBC95 2: project-button \uD074\uB9AD (PC \uBDF0 \uCE74\uB4DC)
									if (viewType === 'projectButton') {
										const projectButtons = document.querySelectorAll('project-button.project-button');
										for (const btn of projectButtons) {
											const titleEl = btn.querySelector('span.project-button-title, .project-button-title');
											if (titleEl && titleEl.textContent.trim() === title) {
												const clickTarget = btn.querySelector('.primary-action-button, mat-card.project-button-card') || btn;
												clickTarget.click();
												return { success: true, method: 'projectButton' };
											}
										}
									}

									// \uBC29\uBC95 3: mat-card \uD074\uB9AD (PC \uBDF0)
									if (viewType === 'matcard') {
										const matCards = document.querySelectorAll('mat-card.project-button-card');
										for (const card of matCards) {
											const titleEl = card.querySelector('span.project-button-title, .project-button-title');
											if (titleEl && titleEl.textContent.trim() === title) {
												const clickTarget = card.querySelector('.primary-action-button') || card;
												clickTarget.click();
												return { success: true, method: 'matcard' };
											}
										}
									}

									// \uBC29\uBC95 4: \uC81C\uBAA9 \uD14D\uC2A4\uD2B8\uB85C \uD074\uB9AD \uAC00\uB2A5\uD55C \uC694\uC18C \uCC3E\uAE30 (\uD3F4\uBC31)
									const allElements = document.querySelectorAll('*');
									for (const el of allElements) {
										if (el.textContent.trim() === title &&
											(el.tagName === 'H2' || el.tagName === 'H3' ||
											 el.className.includes('title') || el.closest('[role="button"]'))) {
											const clickable = el.closest('[role="button"], a, button, [class*="card"], [class*="item"], tr') || el;
											clickable.click();
											return { success: true, method: 'fallback' };
										}
									}

									return { success: false, error: 'Notebook not found: ' + title };
								})();
							`);
            }
            setTimeout(() => {
              this.addSourcesToNotebook(view, notes);
            }, 3e3);
          }
        } else {
          new import_obsidian.Notice(t("notice.creatingNotebook"));
          if (view && view.webview) {
            await view.webview.executeJavaScript(`
							(function() {
								const buttons = document.querySelectorAll('button');
								for (const btn of buttons) {
									const text = (btn.textContent || '').toLowerCase();
									if (text.includes('\uB9CC\uB4E4\uAE30') || text.includes('create')) {
										btn.click();
										return true;
									}
								}
								return false;
							})();
						`);
            setTimeout(async () => {
              await view.webview.executeJavaScript(`
								(function() {
									const closeButtons = document.querySelectorAll('button[aria-label="\uB2EB\uAE30"], button[aria-label="Close"], mat-dialog-container button.close-button, .mat-mdc-dialog-container button[mat-dialog-close], mat-bottom-sheet-container button.close-button');
									for (const btn of closeButtons) {
										if (btn.offsetParent !== null) {
											btn.click();
											return { success: true, method: 'closeButton' };
										}
									}
									const backdrop = document.querySelector('.cdk-overlay-backdrop, .mat-mdc-dialog-container + .cdk-overlay-backdrop');
									if (backdrop) {
										backdrop.click();
										return { success: true, method: 'backdrop' };
									}
									document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', code: 'Escape', keyCode: 27, bubbles: true }));
									return { success: true, method: 'escape' };
								})();
							`);
              await this.delay(500);
              this.addSourcesToNotebook(view, notes);
            }, 3500);
          }
        }
      }
    );
    modal.open();
  }
  // 배치 소스 추가 메서드
  async addSourcesToNotebook(view, notes) {
    const total = notes.length;
    let success = 0;
    let failed = 0;
    for (let i = 0; i < notes.length; i++) {
      const note = notes[i];
      new import_obsidian.Notice(t("notice.batchProgress", { current: i + 1, total, title: note.title }));
      try {
        await this.addSourceToNotebook(view, note);
        success++;
      } catch (error) {
        console.error(`[Star NotebookLM] Failed to add ${note.title}:`, error);
        failed++;
      }
      if (i < notes.length - 1) {
        await this.delay(1e3);
      }
    }
    if (failed === 0) {
      new import_obsidian.Notice(t("notice.batchAllSuccess", { count: success }));
    } else {
      new import_obsidian.Notice(t("notice.batchPartial", { success, failed }));
    }
  }
  // 웹뷰에서 노트북 목록 가져오기
  async getNotebooksFromWebview() {
    const view = this.getNotebookLMView();
    if (!view || !view.webview) {
      return [];
    }
    try {
      const rpcResult = await this.getNotebooksViaRPC(view);
      if (rpcResult && rpcResult.length > 0) {
        return rpcResult;
      }
    } catch (error) {
    }
    try {
      const result = await this.getNotebooksViaDOM(view);
      return result || [];
    } catch (error) {
      console.error("[Star NotebookLM] DOM \uB178\uD2B8\uBD81 \uBAA9\uB85D\uB3C4 \uC2E4\uD328:", error);
      return [];
    }
  }
  // wXbhsf RPC로 노트북 목록 가져오기
  async getNotebooksViaRPC(view) {
    if (!view.webview)
      return [];
    const requestId = "obsidian_list_" + Date.now();
    await view.webview.executeJavaScript(`
			(function() {
				var requestId = "${requestId}";
				window['__obsidian_result_' + requestId] = { pending: true };

				// AT \uD1A0\uD070 \uCD94\uCD9C
				var atToken = null;
				var scripts = document.querySelectorAll('script');
				for (var i = 0; i < scripts.length; i++) {
					var text = scripts[i].textContent || '';
					var match = text.match(/"SNlM0e":"([^"]+)"/);
					if (match) { atToken = match[1]; break; }
				}
				if (!atToken && window.WIZ_global_data && window.WIZ_global_data.SNlM0e) {
					atToken = window.WIZ_global_data.SNlM0e;
				}

				if (!atToken) {
					window['__obsidian_result_' + requestId] = { success: false, pending: false, error: 'No AT token' };
					return;
				}

				var rpcId = 'wXbhsf';
				var requestPayload = [null, 1, null, [2]];
				var requestBody = [[[rpcId, JSON.stringify(requestPayload), null, "generic"]]];

				var formData = new URLSearchParams();
				formData.append('at', atToken);
				formData.append('f.req', JSON.stringify(requestBody));

				var xhr = new XMLHttpRequest();
				xhr.open('POST', '/_/LabsTailwindUi/data/batchexecute?rpcids=' + rpcId, true);
				xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded;charset=UTF-8');
				xhr.withCredentials = true;

				xhr.onload = function() {
					try {
						var text = xhr.responseText;
						if (xhr.status === 200 && text.includes('wrb.fr')) {
							// batchexecute \uC751\uB2F5 \uD30C\uC2F1
							var notebooks = [];
							// ")]}
" \uC811\uB450\uC0AC \uC81C\uAC70 \uD6C4 \uD30C\uC2F1
							var lines = text.split('\\n');
							for (var i = 0; i < lines.length; i++) {
								try {
									var parsed = JSON.parse(lines[i]);
									if (Array.isArray(parsed) && parsed[0] && parsed[0][0] === 'wrb.fr') {
										var innerData = JSON.parse(parsed[0][2]);
										// innerData[0]\uC774 \uB178\uD2B8\uBD81 \uBAA9\uB85D \uBC30\uC5F4
										if (Array.isArray(innerData) && Array.isArray(innerData[0])) {
											innerData[0].forEach(function(nb) {
												if (nb && nb[0]) {
													notebooks.push({
														id: nb[0],
														title: (nb[1] || nb[2] || 'Untitled').toString(),
														url: 'https://notebooklm.google.com/notebook/' + nb[0],
														viewType: 'rpc'
													});
												}
											});
										}
									}
								} catch(e) {}
							}
							window['__obsidian_result_' + requestId] = { success: true, pending: false, notebooks: notebooks };
						} else {
							window['__obsidian_result_' + requestId] = { success: false, pending: false, error: 'API error: ' + xhr.status };
						}
					} catch(e) {
						window['__obsidian_result_' + requestId] = { success: false, pending: false, error: e.message };
					}
				};

				xhr.onerror = function() {
					window['__obsidian_result_' + requestId] = { success: false, pending: false, error: 'Network error' };
				};

				xhr.send(formData.toString());
			})();
		`);
    let result = null;
    for (let i = 0; i < 16; i++) {
      await new Promise((resolve) => setTimeout(resolve, 500));
      result = await view.webview.executeJavaScript(`
				(function() {
					var r = window['__obsidian_result_${requestId}'];
					if (r && !r.pending) {
						delete window['__obsidian_result_${requestId}'];
						return r;
					}
					return null;
				})();
			`);
      if (result)
        break;
    }
    if ((result == null ? void 0 : result.success) && result.notebooks) {
      return result.notebooks;
    }
    return [];
  }
  // DOM 스크래핑으로 노트북 목록 가져오기 (폴백)
  async getNotebooksViaDOM(view) {
    if (!view.webview)
      return [];
    const result = await view.webview.executeJavaScript(`
			(function() {
				var notebooks = [];
				var seen = new Set();

				// \uBC29\uBC95 1: project-table (\uBAA8\uBC14\uC77C/\uC881\uC740 \uD654\uBA74)
				var table = document.querySelector('table.project-table');
				if (table) {
					var rows = table.querySelectorAll('tbody tr, tr');
					rows.forEach(function(row, index) {
						var titleEl = row.querySelector('.project-table-title, [class*="table-title"]');
						if (titleEl) {
							var title = titleEl.textContent.trim();
							if (title && !seen.has(title)) {
								seen.add(title);
								notebooks.push({ id: 'row-' + index, title: title, url: '', viewType: 'table' });
							}
						}
					});
				}

				// \uBC29\uBC95 2: project-button \uC694\uC18C (PC \uCE74\uB4DC \uBDF0)
				if (notebooks.length === 0) {
					var projectButtons = document.querySelectorAll('project-button.project-button');
					projectButtons.forEach(function(btn, index) {
						var titleEl = btn.querySelector('span.project-button-title, .project-button-title');
						if (titleEl) {
							var title = titleEl.textContent.trim();
							if (title && !seen.has(title) && !title.includes('\uC0C8 \uB178\uD2B8') && !title.includes('\uB9CC\uB4E4\uAE30')) {
								seen.add(title);
								notebooks.push({ id: 'projectbtn-' + index, title: title, url: '', viewType: 'projectButton' });
							}
						}
					});
				}

				// \uBC29\uBC95 3: a[href] \uB9C1\uD06C
				if (notebooks.length === 0) {
					document.querySelectorAll('a[href*="/notebook/"]').forEach(function(el) {
						var href = el.getAttribute('href') || '';
						var match = href.match(/\\/notebook\\/([^/\\?]+)/);
						if (match && !seen.has(match[1])) {
							seen.add(match[1]);
							var title = el.textContent.trim() || 'Untitled notebook';
							if (!title.includes('\uC0C8 \uB178\uD2B8') && !title.includes('\uB9CC\uB4E4\uAE30')) {
								notebooks.push({
									id: match[1], title: title,
									url: 'https://notebooklm.google.com' + href, viewType: 'link'
								});
							}
						}
					});
				}

				return notebooks;
			})();
		`);
    return result || [];
  }
  // 노트북 선택 모달 표시
  showNotebookModal(note, notebooks) {
    const modal = new NotebookSelectModal(this.app, this, notebooks, note.title, async (selected) => {
      const view = this.getNotebookLMView();
      if (selected) {
        new import_obsidian.Notice(t("notice.movingToNotebook", { title: selected.title }));
        if (view && view.webview) {
          if (selected.url) {
            view.webview.loadURL(selected.url);
          } else {
            await view.webview.executeJavaScript(`
							(function() {
								const title = ${JSON.stringify(selected.title)};
								const viewType = ${JSON.stringify(selected.viewType || "table")};

								// \uBC29\uBC95 1: \uD14C\uC774\uBE14 \uD589 \uD074\uB9AD (\uBAA8\uBC14\uC77C \uBDF0)
								if (viewType === 'table') {
									const titleEls = document.querySelectorAll('.project-table-title');
									for (const el of titleEls) {
										if (el.textContent.trim() === title) {
											const row = el.closest('tr');
											if (row) {
												row.click();
												return { success: true, method: 'table' };
											}
										}
									}
								}

								// \uBC29\uBC95 2: project-button \uD074\uB9AD (PC \uBDF0 \uCE74\uB4DC)
								if (viewType === 'projectButton') {
									const projectButtons = document.querySelectorAll('project-button.project-button');
									for (const btn of projectButtons) {
										const titleEl = btn.querySelector('span.project-button-title, .project-button-title');
										if (titleEl && titleEl.textContent.trim() === title) {
											// mat-card \uB610\uB294 primary-action-button \uD074\uB9AD
											const clickTarget = btn.querySelector('.primary-action-button, mat-card.project-button-card') || btn;
											clickTarget.click();
											return { success: true, method: 'projectButton' };
										}
									}
								}

								// \uBC29\uBC95 3: mat-card \uD074\uB9AD (PC \uBDF0)
								if (viewType === 'matcard') {
									const matCards = document.querySelectorAll('mat-card.project-button-card');
									for (const card of matCards) {
										const titleEl = card.querySelector('span.project-button-title, .project-button-title');
										if (titleEl && titleEl.textContent.trim() === title) {
											const clickTarget = card.querySelector('.primary-action-button') || card;
											clickTarget.click();
											return { success: true, method: 'matcard' };
										}
									}
								}

								// \uBC29\uBC95 4: \uC81C\uBAA9 \uD14D\uC2A4\uD2B8\uB85C \uD074\uB9AD \uAC00\uB2A5\uD55C \uC694\uC18C \uCC3E\uAE30 (\uD3F4\uBC31)
								const allElements = document.querySelectorAll('*');
								for (const el of allElements) {
									if (el.textContent.trim() === title &&
										(el.tagName === 'H2' || el.tagName === 'H3' ||
										 el.className.includes('title') || el.closest('[role="button"]'))) {
										// \uD074\uB9AD \uAC00\uB2A5\uD55C \uBD80\uBAA8 \uCC3E\uAE30
										const clickable = el.closest('[role="button"], a, button, [class*="card"], [class*="item"], tr') || el;
										clickable.click();
										return { success: true, method: 'fallback' };
									}
								}

								return { success: false, error: 'Notebook not found: ' + title };
							})();
						`);
          }
          setTimeout(() => {
            this.addSourceToNotebook(view, note);
          }, 3e3);
        }
      } else {
        new import_obsidian.Notice(t("notice.creatingNotebook"));
        if (view && view.webview) {
          await view.webview.executeJavaScript(`
						(function() {
							const buttons = document.querySelectorAll('button');
							for (const btn of buttons) {
								const text = (btn.textContent || '').toLowerCase();
								if (text.includes('\uB9CC\uB4E4\uAE30') || text.includes('create')) {
									btn.click();
									return true;
								}
							}
							return false;
						})();
					`);
          setTimeout(async () => {
            await view.webview.executeJavaScript(`
							(function() {
								// \uBC29\uBC95 1: \uB2E4\uC774\uC5BC\uB85C\uADF8 \uB2EB\uAE30 \uBC84\uD2BC \uD074\uB9AD
								const closeButtons = document.querySelectorAll('button[aria-label="\uB2EB\uAE30"], button[aria-label="Close"], mat-dialog-container button.close-button, .mat-mdc-dialog-container button[mat-dialog-close], mat-bottom-sheet-container button.close-button');
								for (const btn of closeButtons) {
									if (btn.offsetParent !== null) {
										btn.click();
										return { success: true, method: 'closeButton' };
									}
								}

								// \uBC29\uBC95 2: \uBC31\uB4DC\uB86D \uD074\uB9AD
								const backdrop = document.querySelector('.cdk-overlay-backdrop, .mat-mdc-dialog-container + .cdk-overlay-backdrop');
								if (backdrop) {
									backdrop.click();
									return { success: true, method: 'backdrop' };
								}

								// \uBC29\uBC95 3: Escape \uD0A4 \uC804\uC1A1
								document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', code: 'Escape', keyCode: 27, bubbles: true }));
								return { success: true, method: 'escape' };
							})();
						`);
            await this.delay(500);
            this.addSourceToNotebook(view, note);
          }, 3500);
        }
      }
    });
    modal.open();
  }
  // 새 노트북 생성 후 소스 추가
  async createNewNotebookAndAddSource(view, note) {
    if (!view.webview)
      return;
    new import_obsidian.Notice(t("notice.creatingNotebookAPI"));
    try {
      const notebookTitle = note.title || "Obsidian Notes";
      const encodedTitle = Buffer.from(notebookTitle, "utf-8").toString("base64");
      const requestId = "obsidian_create_nb_" + Date.now();
      await view.webview.executeJavaScript(`
				(function() {
					function decodeBase64UTF8(base64) {
						var binary = atob(base64);
						var bytes = new Uint8Array(binary.length);
						for (var i = 0; i < binary.length; i++) {
							bytes[i] = binary.charCodeAt(i);
						}
						return new TextDecoder('utf-8').decode(bytes);
					}

					var requestId = "${requestId}";
					var title = decodeBase64UTF8("${encodedTitle}");
					window['__obsidian_result_' + requestId] = { pending: true };

					// AT \uD1A0\uD070 \uCD94\uCD9C
					var atToken = null;
					var scripts = document.querySelectorAll('script');
					for (var i = 0; i < scripts.length; i++) {
						var text = scripts[i].textContent || '';
						var match = text.match(/"SNlM0e":"([^"]+)"/);
						if (match) { atToken = match[1]; break; }
					}
					if (!atToken && window.WIZ_global_data && window.WIZ_global_data.SNlM0e) {
						atToken = window.WIZ_global_data.SNlM0e;
					}

					if (!atToken) {
						window['__obsidian_result_' + requestId] = { success: false, pending: false, error: 'No AT token' };
						return;
					}

					var rpcId = 'CCqFvf';
					var requestPayload = [title, null, null, [2], [1]];
					var requestBody = [[[rpcId, JSON.stringify(requestPayload), null, "generic"]]];

					var formData = new URLSearchParams();
					formData.append('at', atToken);
					formData.append('f.req', JSON.stringify(requestBody));

					var xhr = new XMLHttpRequest();
					xhr.open('POST', '/_/LabsTailwindUi/data/batchexecute?rpcids=' + rpcId, true);
					xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded;charset=UTF-8');
					xhr.withCredentials = true;

					xhr.onload = function() {
						try {
							var text = xhr.responseText;
							if (xhr.status === 200 && text.includes('wrb.fr')) {
								// \uC751\uB2F5\uC5D0\uC11C \uC0C8 \uB178\uD2B8\uBD81 ID \uCD94\uCD9C
								var notebookId = null;
								var lines = text.split('\\n');
								for (var i = 0; i < lines.length; i++) {
									try {
										var parsed = JSON.parse(lines[i]);
										if (Array.isArray(parsed) && parsed[0] && parsed[0][0] === 'wrb.fr') {
											var innerData = JSON.parse(parsed[0][2]);
											if (innerData && innerData[0]) {
												notebookId = innerData[0];
											}
										}
									} catch(e) {}
								}
								window['__obsidian_result_' + requestId] = { success: true, pending: false, notebookId: notebookId };
							} else {
								window['__obsidian_result_' + requestId] = { success: false, pending: false, error: 'API error: ' + xhr.status };
							}
						} catch(e) {
							window['__obsidian_result_' + requestId] = { success: false, pending: false, error: e.message };
						}
					};

					xhr.onerror = function() {
						window['__obsidian_result_' + requestId] = { success: false, pending: false, error: 'Network error' };
					};

					xhr.send(formData.toString());
				})();
			`);
      let result = null;
      for (let i = 0; i < 20; i++) {
        await new Promise((resolve) => setTimeout(resolve, 500));
        result = await view.webview.executeJavaScript(`
					(function() {
						var r = window['__obsidian_result_${requestId}'];
						if (r && !r.pending) {
							delete window['__obsidian_result_${requestId}'];
							return r;
						}
						return null;
					})();
				`);
        if (result)
          break;
      }
      if ((result == null ? void 0 : result.success) && result.notebookId) {
        new import_obsidian.Notice(t("notice.notebookCreated", { title: notebookTitle }));
        view.webview.loadURL("https://notebooklm.google.com/notebook/" + result.notebookId);
        setTimeout(() => {
          this.addSourceToNotebook(view, note);
        }, 3e3);
      } else {
        await this.createNewNotebookViaDOM(view, note);
      }
    } catch (error) {
      console.error("[Star NotebookLM] Create notebook failed:", error);
      await this.createNewNotebookViaDOM(view, note);
    }
  }
  // DOM 방식 노트북 생성 (폴백)
  async createNewNotebookViaDOM(view, note) {
    if (!view.webview)
      return;
    try {
      await view.webview.executeJavaScript(`
				(function() {
					var allButtons = document.querySelectorAll('button');
					for (var i = 0; i < allButtons.length; i++) {
						var text = allButtons[i].textContent.toLowerCase();
						if (text.includes('\uB9CC\uB4E4\uAE30') || text.includes('create') || text.includes('new')) {
							allButtons[i].click();
							return { success: true };
						}
					}
					return { success: false, error: 'Create button not found' };
				})();
			`);
      new import_obsidian.Notice(t("notice.waitingNotebook"));
      setTimeout(() => {
        this.addSourceToNotebook(view, note);
      }, 4e3);
    } catch (error) {
      console.error("[Star NotebookLM] DOM Create notebook failed:", error);
      new import_obsidian.Notice(t("notice.notebookCreateFailed"));
      this.addToQueue(note);
    }
  }
  // 노트북에 소스 추가 (완전 자동화)
  async addSourceToNotebook(view, note) {
    if (!view.webview)
      return;
    if (this.settings.sourceAddMethod === "api") {
      await this.addSourceViaAPI(view, note);
      return;
    }
    await this.addSourceViaDOM(view, note);
  }
  // API 직접 호출 방식으로 소스 추가
  // izAoDd RPC로 텍스트/URL 모두 지원!
  async addSourceViaAPI(view, note) {
    if (!view.webview)
      return;
    if (note.shareLink) {
      await this.addUrlSourceViaAPI(view, note);
      return;
    }
    await this.addTextSourceViaAPI(view, note);
  }
  // 텍스트 소스 API 추가 (izAoDd RPC) - nlm-py에서 검증된 페이로드
  async addTextSourceViaAPI(view, note) {
    if (!view.webview)
      return;
    const title = note.title;
    const content = note.content;
    new import_obsidian.Notice(t("notice.addingTextSource", { title }));
    try {
      const pageInfo = await view.webview.executeJavaScript(`
				(function() {
					const match = window.location.pathname.match(/\\/notebook\\/([^/]+)/);
					const notebookId = match ? match[1] : null;

					let atToken = null;
					const scripts = document.querySelectorAll('script');
					for (const script of scripts) {
						const text = script.textContent || '';
						const tokenMatch = text.match(/"SNlM0e":"([^"]+)"/);
						if (tokenMatch) {
							atToken = tokenMatch[1];
							break;
						}
					}
					if (!atToken && window.WIZ_global_data && window.WIZ_global_data.SNlM0e) {
						atToken = window.WIZ_global_data.SNlM0e;
					}

					return { notebookId, atToken };
				})();
			`);
      if (!pageInfo.notebookId) {
        new import_obsidian.Notice(t("notice.selectNotebookFirst"));
        await this.addSourceViaDOM(view, note);
        return;
      }
      if (!pageInfo.atToken) {
        new import_obsidian.Notice(t("notice.noAuthToken"));
        await this.addSourceViaDOM(view, note);
        return;
      }
      const encodedTitle = Buffer.from(title, "utf-8").toString("base64");
      const encodedContent = Buffer.from(content, "utf-8").toString("base64");
      const requestId = "obsidian_api_" + Date.now();
      await view.webview.executeJavaScript(`
				(function() {
					// UTF-8 Base64 \uB514\uCF54\uB529 \uD568\uC218
					function decodeBase64UTF8(base64) {
						var binary = atob(base64);
						var bytes = new Uint8Array(binary.length);
						for (var i = 0; i < binary.length; i++) {
							bytes[i] = binary.charCodeAt(i);
						}
						return new TextDecoder('utf-8').decode(bytes);
					}

					var notebookId = "${pageInfo.notebookId}";
					var atToken = "${pageInfo.atToken}";
					var title = decodeBase64UTF8("${encodedTitle}");
					var content = decodeBase64UTF8("${encodedContent}");
					var requestId = "${requestId}";

					window['__obsidian_result_' + requestId] = { pending: true };

					var rpcId = 'izAoDd';

					// nlm-py v0.3.4 \uAC80\uC99D \uD14D\uC2A4\uD2B8 \uC18C\uC2A4 \uD398\uC774\uB85C\uB4DC
					var requestPayload = [
						[
							[
								null,
								[title, content],
								null,
								null,
								null,
								null,
								null,
								null
							]
						],
						notebookId,
						[2],
						null,
						null
					];

					var requestBody = [[[rpcId, JSON.stringify(requestPayload), null, "generic"]]];

					var formData = new URLSearchParams();
					formData.append('at', atToken);
					formData.append('f.req', JSON.stringify(requestBody));

					var xhr = new XMLHttpRequest();
					xhr.open('POST', '/_/LabsTailwindUi/data/batchexecute?rpcids=' + rpcId, true);
					xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded;charset=UTF-8');
					xhr.withCredentials = true;

					xhr.onload = function() {
						var text = xhr.responseText;
						if (xhr.status === 200 && text.includes('wrb.fr')) {
							window['__obsidian_result_' + requestId] = { success: true, pending: false };
						} else {
							window['__obsidian_result_' + requestId] = { success: false, pending: false, error: 'API error: ' + xhr.status };
						}
					};

					xhr.onerror = function() {
						window['__obsidian_result_' + requestId] = { success: false, pending: false, error: 'Network error' };
					};

					xhr.send(formData.toString());
				})();
			`);
      let result = null;
      for (let i = 0; i < 20; i++) {
        await new Promise((resolve) => setTimeout(resolve, 500));
        result = await view.webview.executeJavaScript(`
					(function() {
						var r = window['__obsidian_result_${requestId}'];
						if (r && !r.pending) {
							delete window['__obsidian_result_${requestId}'];
							return r;
						}
						return null;
					})();
				`);
        if (result)
          break;
      }
      if (result == null ? void 0 : result.success) {
        new import_obsidian.Notice(t("notice.textSourceAdded", { title }));
      } else {
        new import_obsidian.Notice(t("notice.apiFailed"));
        await this.addSourceViaDOM(view, note);
      }
    } catch (error) {
      console.error("[Star NotebookLM] Text API failed:", error);
      new import_obsidian.Notice(t("notice.apiFailed"));
      await this.addSourceViaDOM(view, note);
    }
  }
  // URL 소스 API 추가 (izAoDd RPC) - 테스트로 검증됨
  async addUrlSourceViaAPI(view, note) {
    if (!view.webview || !note.shareLink)
      return;
    new import_obsidian.Notice(t("notice.addingUrlSource", { title: note.title }));
    try {
      const pageInfo = await view.webview.executeJavaScript(`
				(function() {
					const match = window.location.pathname.match(/\\/notebook\\/([^/]+)/);
					const notebookId = match ? match[1] : null;

					let atToken = null;
					const scripts = document.querySelectorAll('script');
					for (const script of scripts) {
						const text = script.textContent || '';
						const tokenMatch = text.match(/"SNlM0e":"([^"]+)"/);
						if (tokenMatch) {
							atToken = tokenMatch[1];
							break;
						}
					}
					if (!atToken && window.WIZ_global_data && window.WIZ_global_data.SNlM0e) {
						atToken = window.WIZ_global_data.SNlM0e;
					}

					return { notebookId, atToken };
				})();
			`);
      if (!pageInfo.notebookId) {
        new import_obsidian.Notice(t("notice.selectNotebookFirst"));
        return;
      }
      if (!pageInfo.atToken) {
        new import_obsidian.Notice(t("notice.noAuthToken"));
        await this.addLinkSourceToNotebook(view, note);
        return;
      }
      const shareLink = note.shareLink;
      const requestId = "obsidian_url_api_" + Date.now();
      await view.webview.executeJavaScript(`
				(function() {
					var notebookId = "${pageInfo.notebookId}";
					var atToken = "${pageInfo.atToken}";
					var url = "${shareLink}";
					var requestId = "${requestId}";

					window['__obsidian_result_' + requestId] = { pending: true };

					var rpcId = 'izAoDd';
					var requestPayload = [
						[[null, null, [url], null, null, null, null, null, null, null, 1]],
						notebookId,
						[2],
						[1, null, null, null, null, null, null, null, null, null, [1]]
					];
					var requestBody = [[[rpcId, JSON.stringify(requestPayload), null, "generic"]]];

					var formData = new URLSearchParams();
					formData.append('at', atToken);
					formData.append('f.req', JSON.stringify(requestBody));

					var xhr = new XMLHttpRequest();
					xhr.open('POST', '/_/LabsTailwindUi/data/batchexecute?rpcids=' + rpcId, true);
					xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded;charset=UTF-8');
					xhr.withCredentials = true;

					xhr.onload = function() {
						var text = xhr.responseText;
						if (xhr.status === 200 && text.includes('wrb.fr')) {
							window['__obsidian_result_' + requestId] = { success: true, pending: false };
						} else {
							window['__obsidian_result_' + requestId] = { success: false, pending: false, error: 'API error: ' + xhr.status };
						}
					};

					xhr.onerror = function() {
						window['__obsidian_result_' + requestId] = { success: false, pending: false, error: 'Network error' };
					};

					xhr.send(formData.toString());
				})();
			`);
      let result = null;
      for (let i = 0; i < 20; i++) {
        await new Promise((resolve) => setTimeout(resolve, 500));
        result = await view.webview.executeJavaScript(`
					(function() {
						var r = window['__obsidian_result_${requestId}'];
						if (r && !r.pending) {
							delete window['__obsidian_result_${requestId}'];
							return r;
						}
						return null;
					})();
				`);
        if (result)
          break;
      }
      if (result == null ? void 0 : result.success) {
        new import_obsidian.Notice(t("notice.urlSourceAdded", { title: note.title }));
      } else {
        new import_obsidian.Notice(t("notice.apiFailed"));
        await this.addLinkSourceToNotebook(view, note);
      }
    } catch (error) {
      console.error("[Star NotebookLM] URL API failed:", error);
      new import_obsidian.Notice(t("notice.apiFailed"));
      await this.addLinkSourceToNotebook(view, note);
    }
  }
  // DOM 조작 방식으로 소스 추가
  async addSourceViaDOM(view, note) {
    if (!view.webview)
      return;
    const content = "# " + note.title + "\n\n" + note.content;
    new import_obsidian.Notice(t("notice.addingDomSource", { title: note.title }));
    try {
      await view.webview.executeJavaScript(`
				(function() {
					// \uD0ED \uBC84\uD2BC \uCC3E\uAE30 (\uCD9C\uCC98, Sources, \uC18C\uC2A4)
					const tabs = document.querySelectorAll('[role="tab"], button[class*="tab"], mat-tab-header button, .mat-mdc-tab');
					for (const tab of tabs) {
						const text = (tab.textContent || '').trim().toLowerCase();
						if (text.includes('\uCD9C\uCC98') || text.includes('sources') || text.includes('\uC18C\uC2A4')) {
							tab.click();
							return { success: true, tab: text };
						}
					}

					// \uB124\uBE44\uAC8C\uC774\uC158 \uBC14\uC5D0\uC11C \uCC3E\uAE30
					const navItems = document.querySelectorAll('nav button, nav a, [class*="nav"] button');
					for (const item of navItems) {
						const text = (item.textContent || '').trim().toLowerCase();
						if (text.includes('\uCD9C\uCC98') || text.includes('sources') || text.includes('\uC18C\uC2A4')) {
							item.click();
							return { success: true, nav: text };
						}
					}

					// bottom-nav\uB098 tab-bar \uD615\uD0DC\uC77C \uC218 \uC788\uC74C
					const bottomNav = document.querySelectorAll('[class*="bottom-nav"] *, [class*="tab-bar"] *');
					for (const item of bottomNav) {
						const text = (item.textContent || '').trim().toLowerCase();
						if (text.includes('\uCD9C\uCC98') || text.includes('sources')) {
							item.click();
							return { success: true, bottomNav: text };
						}
					}

					return { success: false, error: 'Sources tab not found (might be desktop view)' };
				})();
			`);
      await this.delay(800);
      const step1 = await view.webview.executeJavaScript(`
				(function() {
					// \uC5EC\uB7EC \uC140\uB809\uD130 \uC2DC\uB3C4
					const selectors = [
						'button.add-source-button',
						'button[aria-label="\uCD9C\uCC98 \uCD94\uAC00"]',
						'button[aria-label="\uC5C5\uB85C\uB4DC \uC18C\uC2A4 \uB300\uD654\uC0C1\uC790 \uC5F4\uAE30"]',
						'button.upload-button',
						'button.upload-icon-button'
					];

					for (const sel of selectors) {
						const btn = document.querySelector(sel);
						if (btn && !btn.disabled) {
							btn.click();
							return { success: true, selector: sel };
						}
					}

					// \uD14D\uC2A4\uD2B8\uB85C \uCC3E\uAE30
					const buttons = document.querySelectorAll('button');
					for (const btn of buttons) {
						const text = (btn.textContent || '').trim();
						if (text.includes('\uC18C\uC2A4 \uCD94\uAC00') || text.includes('\uC18C\uC2A4 \uC5C5\uB85C\uB4DC') ||
							text === 'upload' || text.includes('Add source')) {
							btn.click();
							return { success: true, text: text };
						}
					}

					return { success: false, error: 'Source add button not found' };
				})();
			`);
      await this.delay(1500);
      await view.webview.executeJavaScript(`
				(function() {
					// mat-bottom-sheet-container \uB0B4\uBD80\uC758 \uC2A4\uD06C\uB864 \uAC00\uB2A5 \uC601\uC5ED \uCC3E\uAE30
					const bottomSheet = document.querySelector('mat-bottom-sheet-container');
					if (bottomSheet) {
						// bottom-sheet \uC790\uCCB4\uB97C \uC2A4\uD06C\uB864
						bottomSheet.scrollTop = bottomSheet.scrollHeight;
					}

					// upload-dialog-panel \uB0B4\uBD80 \uC2A4\uD06C\uB864
					const panel = document.querySelector('.upload-dialog-panel');
					if (panel) {
						panel.scrollTop = panel.scrollHeight;
						// \uD328\uB110 \uB0B4\uBD80\uC758 \uBAA8\uB4E0 \uC624\uBC84\uD50C\uB85C\uC6B0 \uAC00\uB2A5 \uC694\uC18C \uCC3E\uAE30
						const scrollables = panel.querySelectorAll('*');
						for (const el of scrollables) {
							const style = window.getComputedStyle(el);
							if (style.overflowY === 'auto' || style.overflowY === 'scroll') {
								el.scrollTop = el.scrollHeight;
							}
						}
					}

					// cdk-overlay-pane \uC2A4\uD06C\uB864
					const overlay = document.querySelector('.cdk-overlay-pane');
					if (overlay) {
						overlay.scrollTop = overlay.scrollHeight;
					}
				})();
			`);
      await this.delay(500);
      await view.webview.executeJavaScript(`
				(function() {
					const allElements = document.querySelectorAll('*');
					for (const el of allElements) {
						const text = (el.textContent || '').trim();
						if (text === '\uD14D\uC2A4\uD2B8 \uBD99\uC5EC\uB123\uAE30' || text === 'Paste text') {
							el.scrollIntoView({ behavior: 'smooth', block: 'center' });
							return;
						}
					}
					// \uBABB \uCC3E\uC73C\uBA74 "\uBCF5\uC0AC\uB41C \uD14D\uC2A4\uD2B8"\uB85C \uC2DC\uB3C4
					for (const el of allElements) {
						const text = (el.textContent || '').trim();
						if (text === '\uBCF5\uC0AC\uB41C \uD14D\uC2A4\uD2B8' || text === 'Copied text') {
							el.scrollIntoView({ behavior: 'smooth', block: 'center' });
							return;
						}
					}
				})();
			`);
      await this.delay(800);
      const step2 = await view.webview.executeJavaScript(`
				(function() {
					// "\uBCF5\uC0AC\uB41C \uD14D\uC2A4\uD2B8" \uC9C1\uC811 \uD074\uB9AD \uC2DC\uB3C4
					const allElements = document.querySelectorAll('*');
					for (const el of allElements) {
						const text = (el.textContent || '').trim();
						// \uC815\uD655\uD788 "\uBCF5\uC0AC\uB41C \uD14D\uC2A4\uD2B8" \uB9E4\uCE6D
						if (text === '\uBCF5\uC0AC\uB41C \uD14D\uC2A4\uD2B8' || text === 'Copied text') {
							el.click();
							return { success: true, clicked: text };
						}
					}

					// "\uD14D\uC2A4\uD2B8 \uBD99\uC5EC\uB123\uAE30" \uC139\uC158 \uD074\uB9AD (\uD655\uC7A5 \uD544\uC694\uD560 \uC218 \uC788\uC74C)
					for (const el of allElements) {
						const text = (el.textContent || '').trim();
						if (text === '\uD14D\uC2A4\uD2B8 \uBD99\uC5EC\uB123\uAE30' || text === 'Paste text') {
							el.click();
							return { success: true, clicked: text, needsSecondClick: true };
						}
					}

					return { success: false, error: 'Text paste option not found in DOM' };
				})();
			`);
      if (step2 == null ? void 0 : step2.needsSecondClick) {
        await this.delay(800);
        await view.webview.executeJavaScript(`
					(function() {
						const modal = document.querySelector('.upload-dialog-panel, mat-bottom-sheet-container, [role="dialog"]');
						if (!modal) return { success: false };
						const allElements = modal.querySelectorAll('*');
						for (const el of allElements) {
							const text = (el.textContent || '').trim();
							if (text === '\uBCF5\uC0AC\uB41C \uD14D\uC2A4\uD2B8' || text === 'Copied text') {
								el.click();
								return { success: true };
							}
						}
						return { success: false };
					})();
				`);
      }
      await this.delay(1500);
      const step3 = await view.webview.executeJavaScript(`
				(function() {
					const content = ${JSON.stringify(content)};

					// \uC815\uD655\uD55C \uC140\uB809\uD130: textarea.text-area
					let textarea = document.querySelector('textarea.text-area');

					// \uC5C6\uC73C\uBA74 \uB2E4\uC774\uC5BC\uB85C\uADF8 \uB0B4 textarea \uCC3E\uAE30
					if (!textarea) {
						const modal = document.querySelector('.upload-dialog-panel, [role="dialog"], mat-dialog-container');
						if (modal) {
							textarea = modal.querySelector('textarea');
						}
					}

					if (textarea && textarea.offsetParent !== null) {
						textarea.focus();
						textarea.value = content;
						// Angular/React \uB4F1\uC5D0\uC11C \uAC12 \uBCC0\uACBD \uAC10\uC9C0\uB97C \uC704\uD574 \uC5EC\uB7EC \uC774\uBCA4\uD2B8 \uBC1C\uC0DD
						textarea.dispatchEvent(new Event('input', { bubbles: true }));
						textarea.dispatchEvent(new Event('change', { bubbles: true }));
						textarea.dispatchEvent(new KeyboardEvent('keyup', { bubbles: true }));
						return { success: true };
					}

					return { success: false, error: 'textarea.text-area not found or not visible' };
				})();
			`);
      await this.delay(800);
      const step4 = await view.webview.executeJavaScript(`
				(function() {
					const buttons = document.querySelectorAll('button');
					for (const btn of buttons) {
						const text = (btn.textContent || '').trim();
						if (text === '\uC0BD\uC785' || text === 'Insert') {
							// \uBC84\uD2BC\uC774 \uD65C\uC131\uD654\uB420 \uB54C\uAE4C\uC9C0 \uB300\uAE30
							if (!btn.disabled) {
								btn.click();
								return { success: true };
							} else {
								return { success: false, error: '\uC0BD\uC785 button is disabled' };
							}
						}
					}
					return { success: false, error: '\uC0BD\uC785 button not found' };
				})();
			`);
      if ((step3 == null ? void 0 : step3.success) && (step4 == null ? void 0 : step4.success)) {
        new import_obsidian.Notice(t("notice.sourceAdded", { title: note.title }), 5e3);
      } else if (step3 == null ? void 0 : step3.success) {
        new import_obsidian.Notice(t("notice.manualInsert"), 5e3);
      } else {
        await navigator.clipboard.writeText(content);
        new import_obsidian.Notice(t("notice.clipboardFallback"), 8e3);
      }
    } catch (error) {
      console.error("[Star NotebookLM] Auto add source failed:", error);
      try {
        await navigator.clipboard.writeText(content);
        new import_obsidian.Notice(t("notice.clipboardCopied", { title: note.title }), 8e3);
      } catch (e) {
        new import_obsidian.Notice(t("notice.sourceAddFailed"), 5e3);
      }
    }
  }
  // 링크 소스 추가 (share_link가 있는 노트용)
  async addLinkSourceToNotebook(view, note) {
    if (!view.webview || !note.shareLink)
      return;
    try {
      await view.webview.executeJavaScript(`
				(function() {
					const tabs = document.querySelectorAll('[role="tab"], button[class*="tab"], .mat-mdc-tab');
					for (const tab of tabs) {
						const text = (tab.textContent || '').trim().toLowerCase();
						if (text.includes('\uCD9C\uCC98') || text.includes('sources') || text.includes('\uC18C\uC2A4')) {
							tab.click();
							return { success: true, tab: text };
						}
					}
					return { success: false };
				})();
			`);
      await this.delay(800);
      const step1 = await view.webview.executeJavaScript(`
				(function() {
					const selectors = [
						'button[aria-label="\uCD9C\uCC98 \uCD94\uAC00"]',
						'button[aria-label="\uC18C\uC2A4 \uCD94\uAC00"]',
						'button.add-source-button',
						'button[aria-label="\uC5C5\uB85C\uB4DC \uC18C\uC2A4 \uB300\uD654\uC0C1\uC790 \uC5F4\uAE30"]'
					];
					for (const sel of selectors) {
						const btn = document.querySelector(sel);
						if (btn && !btn.disabled) {
							btn.click();
							return { success: true, selector: sel };
						}
					}
					// \uD14D\uC2A4\uD2B8\uB85C \uCC3E\uAE30
					const buttons = document.querySelectorAll('button');
					for (const btn of buttons) {
						const text = (btn.textContent || '').trim();
						if (text.includes('\uC18C\uC2A4 \uCD94\uAC00') || text.includes('\uC18C\uC2A4 \uC5C5\uB85C\uB4DC')) {
							btn.click();
							return { success: true, text: text };
						}
					}
					return { success: false, error: 'Source add button not found' };
				})();
			`);
      await this.delay(1500);
      await view.webview.executeJavaScript(`
				(function() {
					const m = document.querySelector('mat-bottom-sheet-container, .upload-dialog-panel');
					if (m) m.scrollTop = m.scrollHeight;
					for (const el of document.querySelectorAll('*')) {
						const text = (el.textContent || '').trim();
						if (text === '\uB9C1\uD06C' || text === '\uC6F9\uC0AC\uC774\uD2B8') {
							el.scrollIntoView({ block: 'center' });
							break;
						}
					}
				})();
			`);
      await this.delay(500);
      const step2 = await view.webview.executeJavaScript(`
				(function() {
					for (const el of document.querySelectorAll('*')) {
						const text = (el.textContent || '').trim();
						if (text === '\uB9C1\uD06C') {
							el.click();
							return { success: true, tag: el.tagName };
						}
					}
					return { success: false, error: '\uB9C1\uD06C option not found' };
				})();
			`);
      await this.delay(1e3);
      const step3 = await view.webview.executeJavaScript(`
				(function() {
					for (const el of document.querySelectorAll('span, div, button, a')) {
						const text = (el.textContent || '').trim();
						if (text === '\uC6F9\uC0AC\uC774\uD2B8' || text === 'Website') {
							el.click();
							return { success: true, tag: el.tagName };
						}
					}
					return { success: false, error: '\uC6F9\uC0AC\uC774\uD2B8 option not found' };
				})();
			`);
      await this.delay(2e3);
      const shareLink = note.shareLink;
      const step4 = await view.webview.executeJavaScript(`
				(function() {
					const url = ${JSON.stringify(shareLink)};

					// textarea \uCC3E\uAE30 (\uC6F9\uC0AC\uC774\uD2B8 URL \uB2E4\uC774\uC5BC\uB85C\uADF8)
					const dialogs = document.querySelectorAll('mat-dialog-container, [role="dialog"], .cdk-overlay-pane');
					for (const dialog of dialogs) {
						const text = (dialog.textContent || '');
						if (text.includes('\uC6F9\uC0AC\uC774\uD2B8 URL') || text.includes('URL \uBD99\uC5EC\uB123\uAE30')) {
							const ta = dialog.querySelector('textarea');
							if (ta && ta.offsetParent !== null) {
								ta.focus();
								ta.value = url;
								ta.dispatchEvent(new Event('input', { bubbles: true }));
								ta.dispatchEvent(new Event('change', { bubbles: true }));
								return { success: true, method: 'dialog textarea' };
							}
						}
					}

					// placeholder\uB85C \uCC3E\uAE30
					const textareas = document.querySelectorAll('textarea');
					for (const ta of textareas) {
						const placeholder = (ta.placeholder || '').toLowerCase();
						if (placeholder.includes('url') || placeholder.includes('\uBD99\uC5EC\uB123\uAE30')) {
							if (ta.offsetParent !== null) {
								ta.focus();
								ta.value = url;
								ta.dispatchEvent(new Event('input', { bubbles: true }));
								ta.dispatchEvent(new Event('change', { bubbles: true }));
								return { success: true, method: 'placeholder textarea' };
							}
						}
					}

					// \uC544\uBB34 visible textarea
					for (const ta of textareas) {
						if (ta.offsetParent !== null) {
							ta.focus();
							ta.value = url;
							ta.dispatchEvent(new Event('input', { bubbles: true }));
							ta.dispatchEvent(new Event('change', { bubbles: true }));
							return { success: true, method: 'any visible textarea' };
						}
					}

					return { success: false, error: 'URL textarea not found' };
				})();
			`);
      await this.delay(1e3);
      const step5 = await view.webview.executeJavaScript(`
				(function() {
					const buttons = document.querySelectorAll('button');
					for (const btn of buttons) {
						const text = (btn.textContent || '').trim();
						if (text === '\uC0BD\uC785' || text === 'Insert') {
							if (!btn.disabled) {
								btn.click();
								return { success: true };
							} else {
								return { success: false, error: '\uC0BD\uC785 button is disabled' };
							}
						}
					}
					return { success: false, error: '\uC0BD\uC785 button not found' };
				})();
			`);
      if ((step4 == null ? void 0 : step4.success) && (step5 == null ? void 0 : step5.success)) {
        new import_obsidian.Notice(t("notice.linkSourceAdded", { title: note.title, link: note.shareLink }), 5e3);
      } else if (step4 == null ? void 0 : step4.success) {
        new import_obsidian.Notice(t("notice.manualUrlInsert"), 5e3);
      } else {
        await navigator.clipboard.writeText(note.shareLink);
        new import_obsidian.Notice(t("notice.urlClipboardFallback", { link: note.shareLink }), 8e3);
      }
    } catch (error) {
      console.error("[Star NotebookLM] Link source add failed:", error);
      try {
        await navigator.clipboard.writeText(note.shareLink);
        new import_obsidian.Notice(t("notice.urlClipboardCopied", { title: note.title }), 8e3);
      } catch (e) {
        new import_obsidian.Notice(t("notice.linkAddFailed"), 5e3);
      }
    }
  }
  delay(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }
  // 디버그: 웹뷰 DOM 정보 수집
  async debugWebviewDOM() {
    const view = this.getNotebookLMView();
    if (!view || !view.webview) {
      new import_obsidian.Notice(t("notice.webviewNotOpen"));
      return;
    }
    new import_obsidian.Notice(t("notice.collectingDom"));
    try {
      const domInfo = await view.webview.executeJavaScript(`
				(function() {
					const info = {
						url: window.location.href,
						title: document.title,
						buttons: [],
						clickableElements: [],
						textInputs: [],
						dialogs: [],
						notebookLinks: []
					};

					// \uBAA8\uB4E0 \uBC84\uD2BC \uC815\uBCF4
					document.querySelectorAll('button').forEach((btn, i) => {
						info.buttons.push({
							index: i,
							text: (btn.textContent || '').trim().substring(0, 50),
							ariaLabel: btn.getAttribute('aria-label'),
							className: btn.className.substring(0, 100),
							disabled: btn.disabled,
							visible: btn.offsetParent !== null
						});
					});

					// role="button" \uC694\uC18C\uB4E4
					document.querySelectorAll('[role="button"]').forEach((el, i) => {
						info.clickableElements.push({
							index: i,
							tagName: el.tagName,
							text: (el.textContent || '').trim().substring(0, 50),
							ariaLabel: el.getAttribute('aria-label'),
							className: el.className.substring(0, 100)
						});
					});

					// \uD14D\uC2A4\uD2B8 \uC785\uB825 \uD544\uB4DC
					document.querySelectorAll('textarea, input[type="text"], input:not([type]), [contenteditable="true"]').forEach((el, i) => {
						info.textInputs.push({
							index: i,
							tagName: el.tagName,
							placeholder: el.getAttribute('placeholder'),
							className: el.className.substring(0, 100),
							visible: el.offsetParent !== null
						});
					});

					// \uB2E4\uC774\uC5BC\uB85C\uADF8/\uBAA8\uB2EC
					document.querySelectorAll('[role="dialog"], [role="modal"], [class*="dialog"], [class*="modal"]').forEach((el, i) => {
						info.dialogs.push({
							index: i,
							tagName: el.tagName,
							role: el.getAttribute('role'),
							className: el.className.substring(0, 100),
							visible: el.offsetParent !== null,
							innerText: (el.textContent || '').trim().substring(0, 200)
						});
					});

					// \uB178\uD2B8\uBD81 \uB9C1\uD06C \uC815\uBCF4 \uC218\uC9D1 (a \uD0DC\uADF8)
					document.querySelectorAll('a[href*="/notebook/"]').forEach((el, i) => {
						const href = el.getAttribute('href') || '';
						const parent = el.closest('[class*="card"], [class*="item"], [class*="project"]');
						let title = '';
						if (parent) {
							const titleEl = parent.querySelector('[class*="title"], [class*="name"], h1, h2, h3');
							if (titleEl) title = titleEl.textContent.trim();
						}
						if (!title) title = el.textContent.trim();

						info.notebookLinks.push({
							index: i,
							href: href,
							title: title.substring(0, 100),
							parentClass: parent ? parent.className.substring(0, 100) : null,
							type: 'a-tag'
						});
					});

					// \uD504\uB85C\uC81D\uD2B8/\uB178\uD2B8\uBD81 \uCE74\uB4DC \uC694\uC18C \uC218\uC9D1
					info.projectCards = [];
					document.querySelectorAll('[class*="project-card"], [class*="notebook"], mat-card, [class*="card"]').forEach((el, i) => {
						const text = (el.textContent || '').trim().substring(0, 100);
						const link = el.querySelector('a');
						info.projectCards.push({
							index: i,
							tagName: el.tagName,
							className: el.className.substring(0, 150),
							text: text,
							hasLink: !!link,
							linkHref: link ? link.getAttribute('href') : null
						});
					});

					// \uD074\uB9AD \uAC00\uB2A5\uD55C project \uAD00\uB828 \uC694\uC18C
					info.projectItems = [];
					document.querySelectorAll('[class*="project"]').forEach((el, i) => {
						if (i < 30) { // \uCC98\uC74C 30\uAC1C\uB9CC
							info.projectItems.push({
								index: i,
								tagName: el.tagName,
								className: el.className.substring(0, 150),
								text: (el.textContent || '').trim().substring(0, 80)
							});
						}
					});

					return info;
				})();
			`);
      const debugContent = JSON.stringify(domInfo, null, 2);
      const debugPath = "notebooklm-debug.json";
      await this.app.vault.adapter.write(debugPath, debugContent);
      new import_obsidian.Notice(t("notice.domSaved", { path: debugPath, buttons: domInfo.buttons.length, links: domInfo.notebookLinks.length, inputs: domInfo.textInputs.length, dialogs: domInfo.dialogs.length }), 8e3);
    } catch (error) {
      console.error("[Star NotebookLM] Debug failed:", error);
      new import_obsidian.Notice(t("notice.domFailed", { error: error.message }));
    }
  }
  async sendTextToQueue(text, title) {
    const note = {
      title,
      content: text,
      path: ""
    };
    await this.openNotebookLMView();
    const view = this.getNotebookLMView();
    if (view && view.webview) {
      new import_obsidian.Notice(t("notice.fetchingNotebooks"));
      view.webview.loadURL("https://notebooklm.google.com");
      setTimeout(async () => {
        const notebooks = await this.getNotebooksFromWebview();
        this.showNotebookModal(note, notebooks);
      }, 3e3);
    } else {
      this.showNotebookModal(note, []);
    }
  }
  addToQueue(note) {
    const id = `note-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
    this.noteQueue.set(id, {
      id,
      note,
      timestamp: Date.now(),
      status: "pending"
    });
    this.updateStatusBar();
  }
};
var NotebookLMView = class extends import_obsidian.ItemView {
  // Electron webview
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return NOTEBOOKLM_VIEW_TYPE;
  }
  getDisplayText() {
    return t("view.displayText");
  }
  getIcon() {
    return "book-open";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("notebooklm-view-container");
    const toolbar = container.createDiv("notebooklm-toolbar");
    const refreshBtn = toolbar.createEl("button", { text: t("view.refresh") });
    refreshBtn.onclick = () => this.refresh();
    const listBtn = toolbar.createEl("button", { text: t("view.notebookList") });
    listBtn.onclick = () => this.goToNotebookList();
    this.webviewEl = container.createDiv("notebooklm-webview-container");
    const webviewHtml = `<webview
			id="notebooklm-webview"
			class="notebooklm-webview"
			src="https://notebooklm.google.com"
			style="width: 100%; height: 100%;"
			allowpopups
			partition="persist:notebooklm"
		></webview>`;
    this.webviewEl.innerHTML = webviewHtml;
    this.webview = this.webviewEl.querySelector("webview");
    if (this.webview) {
      this.webview.addEventListener("dom-ready", () => {
        this.injectScript();
      });
      this.webview.addEventListener("ipc-message", (event) => {
        this.handleWebviewMessage(event);
      });
      this.webview.addEventListener("did-navigate", (event) => {
      });
    }
  }
  async onClose() {
  }
  refresh() {
    if (this.webview) {
      this.webview.reload();
    }
  }
  goToNotebookList() {
    if (this.webview) {
      this.webview.loadURL("https://notebooklm.google.com");
    }
  }
  // 웹뷰에 스크립트 삽입
  async injectScript() {
    if (!this.webview)
      return;
    const script = `
			(function() {
				if (window.__obsidianBridgeInjected) return;
				window.__obsidianBridgeInjected = true;


				// \uD398\uC774\uC9C0 \uC0C1\uD0DC \uBD84\uC11D
				function analyzePageState() {
					const path = window.location.pathname;
					const state = {
						path: path,
						isNotebookList: path === '/' || path === '',
						isInsideNotebook: path.includes('/notebook/'),
						notebookId: null,
						notebookTitle: null
					};

					if (state.isInsideNotebook) {
						const match = path.match(/\\/notebook\\/([^/]+)/);
						if (match) state.notebookId = match[1];

						// \uB178\uD2B8\uBD81 \uC81C\uBAA9 \uCC3E\uAE30
						const titleEl = document.querySelector('h1, [class*="title"]');
						if (titleEl) state.notebookTitle = titleEl.textContent.trim();
					}

					return state;
				}

				// \uB178\uD2B8\uBD81 \uBAA9\uB85D \uAC00\uC838\uC624\uAE30
				function getNotebookList() {
					const notebooks = [];
					// NotebookLM\uC758 \uB178\uD2B8\uBD81 \uCE74\uB4DC/\uB9C1\uD06C \uCC3E\uAE30
					document.querySelectorAll('a[href*="/notebook/"]').forEach(el => {
						const href = el.getAttribute('href');
						const match = href.match(/\\/notebook\\/([^/]+)/);
						if (match) {
							notebooks.push({
								id: match[1],
								title: el.textContent.trim() || 'Untitled',
								url: href
							});
						}
					});
					return notebooks;
				}

				// \uC18C\uC2A4 \uCD94\uAC00 \uD568\uC218
				async function addSource(content, title) {

					// "Add source" \uBC84\uD2BC \uCC3E\uAE30
					const addBtnSelectors = [
						'button[aria-label*="Add"]',
						'button[aria-label*="source"]',
						'[class*="add-source"]',
						'button:has(span:contains("Add"))'
					];

					let addBtn = null;
					for (const sel of addBtnSelectors) {
						try {
							addBtn = document.querySelector(sel);
							if (addBtn) break;
						} catch(e) {}
					}

					if (addBtn) {
						addBtn.click();
						await new Promise(r => setTimeout(r, 500));
					}

					// "Copied text" \uC635\uC158 \uCC3E\uAE30
					const textOptionSelectors = [
						'[role="menuitem"]',
						'button',
						'div[class*="option"]'
					];

					for (const sel of textOptionSelectors) {
						const els = document.querySelectorAll(sel);
						for (const el of els) {
							if (el.textContent.includes('Copied text') ||
								el.textContent.includes('Paste') ||
								el.textContent.includes('\uD14D\uC2A4\uD2B8')) {
								el.click();
								await new Promise(r => setTimeout(r, 500));
								break;
							}
						}
					}

					// textarea \uCC3E\uC544\uC11C \uB0B4\uC6A9 \uC785\uB825
					const textarea = document.querySelector('textarea, [contenteditable="true"]');
					if (textarea) {
						const fullContent = '# ' + title + '\\n\\n' + content;
						if (textarea.tagName === 'TEXTAREA') {
							textarea.value = fullContent;
							textarea.dispatchEvent(new Event('input', { bubbles: true }));
						} else {
							textarea.textContent = fullContent;
							textarea.dispatchEvent(new InputEvent('input', { bubbles: true }));
						}
						await new Promise(r => setTimeout(r, 300));

						// \uD655\uC778 \uBC84\uD2BC \uD074\uB9AD
						const confirmBtn = Array.from(document.querySelectorAll('button')).find(
							btn => btn.textContent.includes('Insert') ||
								   btn.textContent.includes('Add') ||
								   btn.textContent.includes('\uCD94\uAC00')
						);
						if (confirmBtn) {
							confirmBtn.click();
							return { success: true };
						}
					}

					// \uC2E4\uD328 \uC2DC \uD074\uB9BD\uBCF4\uB4DC\uC5D0 \uBCF5\uC0AC
					const fullContent = '# ' + title + '\\n\\n' + content;
					await navigator.clipboard.writeText(fullContent);
					return { success: false, clipboard: true };
				}

				// \uBA54\uC2DC\uC9C0 \uB9AC\uC2A4\uB108
				window.addEventListener('message', async (event) => {
					if (event.data.type === 'obsidian-bridge') {
						const { action, payload } = event.data;
						let result = null;

						switch(action) {
							case 'getPageState':
								result = analyzePageState();
								break;
							case 'getNotebooks':
								result = getNotebookList();
								break;
							case 'addSource':
								result = await addSource(payload.content, payload.title);
								break;
							case 'navigateTo':
								window.location.href = payload.url;
								result = { success: true };
								break;
						}

						// \uACB0\uACFC \uC804\uC1A1
						if (window.require) {
							const { ipcRenderer } = window.require('electron');
							ipcRenderer.sendToHost('obsidian-bridge-response', { action, result });
						}
					}
				});

				// \uCD08\uAE30 \uC0C1\uD0DC \uC804\uC1A1
				setTimeout(() => {
					const state = analyzePageState();
					if (window.require) {
						const { ipcRenderer } = window.require('electron');
						ipcRenderer.sendToHost('obsidian-bridge-response', {
							action: 'pageStateChanged',
							result: state
						});
					}
				}, 1000);

				// URL \uBCC0\uACBD \uAC10\uC9C0
				let lastPath = window.location.pathname;
				setInterval(() => {
					if (window.location.pathname !== lastPath) {
						lastPath = window.location.pathname;
						const state = analyzePageState();
						if (window.require) {
							const { ipcRenderer } = window.require('electron');
							ipcRenderer.sendToHost('obsidian-bridge-response', {
								action: 'pageStateChanged',
								result: state
							});
						}
					}
				}, 1000);
			})();
		`;
    try {
      await this.webview.executeJavaScript(script);
    } catch (error) {
      console.error("[NotebookLM] Script injection failed:", error);
    }
  }
  // 웹뷰로 메시지 보내기
  sendToWebview(action, payload) {
    if (this.webview) {
      this.webview.executeJavaScript(`
				window.postMessage({ type: 'obsidian-bridge', action: '${action}', payload: ${JSON.stringify(payload || {})} }, '*');
			`);
    }
  }
  // 웹뷰 메시지 처리
  handleWebviewMessage(event) {
    const { action, result } = event.args[0] || {};
    if (action === "pageStateChanged") {
      this.plugin.currentPageState = result;
      this.plugin.updateStatusBar();
    }
  }
  // 대기열에서 노트 추가
  async addFromQueue() {
    var _a;
    const pendingNotes = Array.from(this.plugin.noteQueue.entries()).filter(([, item2]) => item2.status === "pending");
    if (pendingNotes.length === 0) {
      new import_obsidian.Notice(t("notice.emptyQueue"));
      return;
    }
    if (!((_a = this.plugin.currentPageState) == null ? void 0 : _a.isInsideNotebook)) {
      new import_obsidian.Notice(t("notice.selectNotebook"));
      return;
    }
    const [id, item] = pendingNotes[0];
    new import_obsidian.Notice(t("notice.addingFromQueue", { title: item.note.title }));
    this.sendToWebview("addSource", {
      title: item.note.title,
      content: item.note.content
    });
    setTimeout(() => {
      this.plugin.noteQueue.delete(id);
      this.plugin.updateStatusBar();
      new import_obsidian.Notice(t("notice.addedFromQueue", { title: item.note.title }));
    }, 2e3);
  }
};
var NotebookSelectModal = class extends import_obsidian.Modal {
  constructor(app, plugin, notebooks, noteTitle, onSelect) {
    super(app);
    this.plugin = plugin;
    this.notebooks = notebooks;
    this.noteTitle = noteTitle;
    this.onSelect = onSelect;
  }
  onOpen() {
    this.renderContent();
  }
  renderContent() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("notebooklm-select-modal");
    const headerDiv = contentEl.createDiv("modal-header-row");
    headerDiv.style.display = "flex";
    headerDiv.style.justifyContent = "space-between";
    headerDiv.style.alignItems = "center";
    headerDiv.createEl("h2", { text: t("modal.selectNotebook") });
    const refreshBtn = headerDiv.createEl("button", { text: t("modal.refresh"), cls: "mod-cta" });
    refreshBtn.style.fontSize = "12px";
    refreshBtn.style.padding = "4px 12px";
    refreshBtn.onclick = async () => {
      refreshBtn.textContent = t("modal.loading");
      refreshBtn.disabled = true;
      try {
        this.notebooks = await this.plugin.getNotebooksFromWebview();
        this.renderContent();
      } catch (e) {
        refreshBtn.textContent = t("modal.refresh");
        refreshBtn.disabled = false;
        new import_obsidian.Notice(t("notice.refreshFailed"));
      }
    };
    contentEl.createEl("p", {
      text: t("modal.whereToAdd", { title: this.noteTitle }),
      cls: "modal-description"
    });
    const newSection = contentEl.createDiv("modal-section");
    newSection.createEl("h3", { text: t("modal.newNotebook") });
    const newItem = newSection.createDiv("notebook-item new");
    newItem.innerHTML = `
			<span class="notebook-icon">+</span>
			<div class="notebook-info">
				<span class="notebook-title">${t("modal.createNew")}</span>
				<span class="notebook-desc">${t("modal.createNewDesc")}</span>
			</div>
		`;
    newItem.onclick = () => {
      this.onSelect(null);
      this.close();
    };
    if (this.notebooks.length > 0) {
      const existingSection = contentEl.createDiv("modal-section");
      existingSection.createEl("h3", { text: t("modal.existingNotebooks", { count: this.notebooks.length }) });
      const list = existingSection.createDiv("notebook-list");
      this.notebooks.forEach((notebook) => {
        const item = list.createDiv("notebook-item");
        item.innerHTML = `
					<span class="notebook-icon">\u{1F4D3}</span>
					<div class="notebook-info">
						<span class="notebook-title">${notebook.title}</span>
					</div>
				`;
        item.onclick = () => {
          this.onSelect(notebook);
          this.close();
        };
      });
    } else {
      const emptyMsg = contentEl.createDiv("empty-message");
      emptyMsg.innerHTML = `
				<p>${t("modal.noNotebooks")}</p>
				<p class="hint">${t("modal.noNotebooksHint")}</p>
			`;
    }
    const footer = contentEl.createDiv("modal-footer");
    const cancelBtn = footer.createEl("button", { text: t("modal.cancel") });
    cancelBtn.onclick = () => this.close();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var StarNotebookLMSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: t("settings.title") });
    new import_obsidian.Setting(containerEl).setName(t("settings.language")).setDesc(t("settings.languageDesc")).addDropdown((dropdown) => dropdown.addOption("auto", t("settings.langAuto")).addOption("ko", t("settings.langKo")).addOption("en", t("settings.langEn")).setValue(this.plugin.settings.language).onChange(async (value) => {
      this.plugin.settings.language = value;
      currentLang = getLanguage(this.plugin.settings.language);
      await this.plugin.saveSettings();
      this.display();
    }));
    new import_obsidian.Setting(containerEl).setName(t("settings.includeMetadata")).setDesc(t("settings.includeMetadataDesc")).addToggle((toggle) => toggle.setValue(this.plugin.settings.includeMetadata).onChange(async (value) => {
      this.plugin.settings.includeMetadata = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName(t("settings.includeFrontmatter")).setDesc(t("settings.includeFrontmatterDesc")).addToggle((toggle) => toggle.setValue(this.plugin.settings.includeFrontmatter).onChange(async (value) => {
      this.plugin.settings.includeFrontmatter = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName(t("settings.sourceMethod")).setDesc(t("settings.sourceMethodDesc")).addDropdown((dropdown) => dropdown.addOption("api", t("settings.sourceApi")).addOption("dom", t("settings.sourceDom")).setValue(this.plugin.settings.sourceAddMethod).onChange(async (value) => {
      this.plugin.settings.sourceAddMethod = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: t("settings.usage") });
    const usageList = containerEl.createEl("div");
    usageList.style.marginLeft = "8px";
    usageList.createEl("p", {
      text: t("settings.usage1")
    });
    usageList.createEl("p", {
      text: t("settings.usage2")
    });
    usageList.createEl("p", {
      text: t("settings.usage3")
    });
    const methodList = usageList.createEl("ul");
    methodList.style.marginLeft = "16px";
    methodList.style.marginTop = "4px";
    methodList.createEl("li", {
      text: t("settings.usageMethod1")
    });
    methodList.createEl("li", {
      text: t("settings.usageMethod2")
    });
    methodList.createEl("li", {
      text: t("settings.usageMethod3")
    });
    methodList.createEl("li", {
      text: t("settings.usageMethod4")
    });
    usageList.createEl("p", {
      text: t("settings.usage4")
    });
  }
};

/* nosourcemap */